robotology/robotology-superbuild

CMakeLists.txt
=> To not pollute the source directory with generated robotology-superbuild.dot

CMakeLists.txt
Fix https://github.com/robotology/robotology-superbuild/issues/18 .
=> Bump YCM_TAG to e9bfa3968c1141d8e5a416f648b0a862cf857e2e

README.md
See comments in https://github.com/robotology/robotology-superbuild/pull/31#issuecomment-362313856
=> [doc] Fix YARP_DATA_DIRS definitions in the README

.travis.yml, CMakeLists.txt, README.md, cmake/Buildfastcdr.cmake, cmake/Buildihmc-ors-yarp.cmake
This pull request includes the logic to add the package ihmc-ors-yarp. 
In particular, it has been created a new profile named `ROBOTOLOGY_ENABLE_IHMC` and has been updated the documentation.
=> Add ROBOTOLOGY_ENABLE_IHMC profile

README.md
At this point, I think we can expect the superbuild to actually work.
=> Remove warning at the beginning of the readme

README.md
Fix https://github.com/robotology/robotology-superbuild/issues/49
=> Document how to install ipopt in homebrew

README.md
=> Fix YCM link

cmake/BuildICUB.cmake
Fix https://github.com/robotology/robotology-superbuild/issues/72
=> Enable rpath in ICUB

cmake/ProjectsTagsMaster.cmake
RTF master is again compatible with YARP master.
See https://github.com/robotology/robot-testing/pull/100 .
=> Use again RTF from master

cmake/BuildYARP.cmake
See https://github.com/robotology/robotology-superbuild/issues/167
=> Add ENABLE_yarpmod_SDLJoypad option to YARP

cmake/Buildicub-gazebo-wholebody.cmake
Fix https://github.com/robotology/robotology-superbuild/issues/77
=> Fix icub-gazebo-wholebody repo location

README.md, cmake/ProjectsTagsMaster.cmake, cmake/template/addPathsToUserEnvVariables.ps1.in, cmake/template/removePathsFromUserEnvVariables.ps1.in, cmake/template/setup.bat.in, cmake/template/setup.sh.in
This PR adds the support to the new wb-toolbox v5.
@traversaro Let's wait the announcement before merging.
=> wb-toolbox v5

.ci/install_debian.sh, .ci/install_debian_and_script.sh, .travis.yml
=> Enable ccache in linux travis jobs

cmake/ProjectsTagsMaster.cmake
Workaround for https://github.com/robotology/robotology-superbuild/issues/208
=> Fix RTF version to 1.6.0

README.md
See dartsim/homebrew-dart#76 for a related discussion.
@lrapetti @nunoguedelha Can you check if the ipopt formula from homebrew core  is working correctly? Thanks!
=> Update README to install ipopt from homebrew core

README.md
I added the entry point to the whole-body-controllers installation.
=> Added entry point to WBC installation

README.md
=> VS 2019 support

README.md
Related discussion in https://github.com/robotology/robotology-superbuild/issues/169.
=> Update README with opencv details for MacOS

.ci/install_debian.sh, README.md
libedit ( http://thrysoee.dk/editline/ ) is a YARP optional dependency, see https://github.com/robotology/yarp/issues/2099 .
=> Add libedit installation to README and Continuous Integration

README.md
This PR should fix issue #256 
@traversaro
=> Fix setup environment instructions on Linux system

README.md
The dependencies are related to the options `ROBOTOLOGY_ENABLE_ICUB_HEAD` and `ROBOTOLOGY_ENABLE_DYNAMICS`.
=> Updated README.md with global system related dependencies

doc/change-project-tags.md
Fix https://github.com/robotology/robotology-superbuild/issues/285 .
=> Fix links in change-project-tags doc file

.github/workflows/ci.yml
Fix https://github.com/robotology/robotology-superbuild/issues/101 .
This PR is currently blocked by: 
* ~~https://github.com/robotology/robotology-superbuild/pull/275~~
* ~~https://github.com/robotology/wearables/issues/57 (@Yeshasvitvs as mantainer of the Human Dynamics profile can you ensure that this is addressed, eventually pinging @DanielePucci for obtaining resources? Thanks!)~~ Blocked by https://github.com/robotology/wearables/issues/56
=> Add CI for unstable branches

CMakeLists.txt
=> Add temporary fix for YCM on Windows

.github/workflows/ci.yml
After the fix in https://github.com/robotology/human-dynamics-estimation/pull/174 .
=> Re-enable Human Dynamics component in GitHub Actions

.github/workflows/ci.yml
Remove workaround for https://github.com/robotology/blockfactory/pull/45
=> Test DYNAMICS profile under Windows

.github/workflows/ci.yml, README.md
Updated both the GitHub Action and the README.
=> Use default opencv in Homebrew on macOS

.github/workflows/icubTechIIT_code.yml
This commit will integrate a new GitHub action that links the `robotology/robotology-superbuild`  repository to the `icub-tech-iit/code` repository. 
It will send a command `superbuild_release`, with a payload reporting the current version of the superbuild and the command issued. This will trigger the automatic build and upload of the `Superbuild Docker Image`.
=> Creation of webhook to icub-tech-iit/code

README.md
Related to https://github.com/robotology/yarp/issues/2226
=> Fix the name of the vcpkg directory to append in the PATH

README.md
What do you think about this @simeonedussoni ? If you think it is an improvement, feel free to approve the PR.
=> README: Clarify initial windows dependency installation

README.md
Fixes https://github.com/robotology/robotology-superbuild/issues/37.
=> Documented a few options of the xcodebuild command in the main README

README.md, doc/developer-faqs.md, doc/developers-faqs.md
The contents of the Dev FAQs for now are:
* How to add a new package to the superbuild
* How to add a new  profile 
* How to make a new releases
More material can be added in the future.
It could make sense that this material could be reviewed by someone in the team-code @vtikha , as they are aspects they may need to deal with in the future. 
Fix https://github.com/robotology/robotology-superbuild/issues/142
=> Add Developers Frequently Asked Questions

releases/2020.05.yaml
Fix https://github.com/robotology/robotology-superbuild/issues/387 .
=> Update 2020.05.yml for the upcoming release

CMakeLists.txt, cmake/Buildblocktest-yarp-plugins.cmake, cmake/Buildblocktestcore.cmake
The right name of the package is `blocktestcore`.
please review code
=> blocktest: fix with the right package name

.github/workflows/icubTechIIT_code.yml
Updated the name of the secret token used by team code to point to the new token created for this effect.
=> changed the name of team code secret token

cmake/ProjectsTagsStable.cmake, cmake/ProjectsTagsUnstable.cmake
As https://github.com/robotology/yarp/pull/2356 has been merged.
=> Restore regular YARP branches

README.md
Fix https://github.com/robotology/robotology-superbuild/issues/67 .
Let me know if this is ok for you @GiulioRomualdi .
=> Document YCM_EP_ADDITIONAL_CMAKE_ARGS  to pass CMake option to the subprojects

README.md, scripts/robotologyGitStatus.sh
It also removed a couple of blank spaces at the end of the lines (Atom did).
=> Add script to get the git status of each subfolder.

cmake/BuildBlockFactory.cmake
Can you try this modification and if it works approve the PR @lnobile ? Thanks!
=> Fix compilation of BlockFactory when ROBOTOLOGY_NOT_USE_SIMULINK is ON

CMakeLists.txt, cmake/Buildyarp-device-xsensmt.cmake, releases/2020.11.yaml
See https://github.com/robotology/yarp-device-xsensmt/issues/24 .
=> Change name of xsensmt driver from xsensmt-yarp-driver to yarp-device-xsensmt 

releases/2020.02.yaml, releases/2020.05.feat-01.yaml, releases/2020.05.yaml, releases/2020.08.patch-01.yaml, releases/2020.08.yaml, releases/2020.11.yaml
This PR adds up the packages related to FW in order to be able to produce the corresponding SW Versioning Table.
=> Add FW versions

.github/workflows/ci.yml
Remove old workaround, and add new workaround for  https://github.com/actions/virtual-environments/issues/2248
=> Fix Homebrew CI

scripts/robotologyGitStatus.sh
Fixes https://github.com/robotology/robotology-superbuild/pull/557#discussion_r542409491
=> Removed unnecessary tag in git status

releases/2020.08.feat-01.yaml
There was a typo in the first YAML element
=> Fix 2020.08.feat-01.yaml

.ci/initial-cache.gh.cmake
They were accidentally set to OFF.
=> Enable ROBOTOLOGY_USES_OCTAVE and ROBOTOLOGY_USES_PYTHON in CI

cmake/ProjectsTagsStable.cmake, releases/latest.releases.yaml
Consequence of  https://github.com/coin-or/CppAD/pull/95
=> Bump the version of CppAD

releases/latest.releases.yaml
I still did not copied this to the `2021.02.yaml`, but these tags will all probably be part of 2021.02 @Nicogene .
=> Update some projects to their latest tags

cmake/ProjectsTagsUnstable.cmake
To be merged after https://github.com/dic-iit/bipedal-locomotion-framework/pull/239/files .
=> Update manif version in ProjectTagsUnstable

.github/workflows/ci.yml
Issues:
* https://github.com/robotology/robotology-superbuild/issues/571 solved in https://github.com/actions/virtual-environments/issues/2391 
* https://github.com/robotology/robotology-superbuild/issues/565 solved in https://github.com/actions/virtual-environments/issues/2322
=> Remove workarounds for solved Homebrew issues

releases/latest.releases.yaml
* Do not update WB-Toolbox until https://github.com/robotology/wb-toolbox/issues/219 is fixed
* Manually update icub-firmware e icub-firmware-build
* Run CI that was skipped in https://github.com/robotology/robotology-superbuild/pull/761
=> Change manually latest.releases.yaml

CHANGELOG.md
Several changes were done but without updating the CHANGELOG.
=> Update CHANGELOG with improvements from the last period

doc/install-mambaforge.md
Fix https://github.com/robotology/robotology-superbuild/issues/811
=> Document Powershell pitfalls and possible problems

.github/workflows/ci.yml, CHANGELOG.md, apt.txt, cmake/BuildiDynTree.cmake, doc/conda-forge.md, doc/deprecated-installation-methods.md
Fix https://github.com/robotology/robotology-superbuild/issues/917 .
=> Add assimp dependency

doc/change-project-tags.md
That part was not updated in https://github.com/robotology/robotology-superbuild/pull/556 .
=> Update docs on remove source directory

CHANGELOG.md, releases/2021.11.1.yaml
* Update CHANGELOG.md
* Create `releases/2021.11.1.yaml` file
=> Bring 2021.11.1 files to master branch

cmake/Buildbipedal-locomotion-framework.cmake
=> Add YARP_telemetry on the bipedal-locomotion-framework dependencies

cmake/Buildicub-models.cmake
See https://github.com/robotology/icub-models/pull/130 .
=> Add support for Python helper library of icub-models

cmake/BuildqpOASES.cmake
We need to merge this as soon as https://github.com/conda-forge/staged-recipes/pull/18384 is merged.
=> qpOASES: Switch to use conda-forge conda packages instead of building custom one for robotology channel

CHANGELOG.md, releases/2022.02.1.yaml
From https://github.com/robotology/robotology-superbuild/pull/1080 .
=> Add files for 2022.02.1 release

cmake/ProjectsTagsStable.cmake, cmake/ProjectsTagsUnstable.cmake, releases/latest.releases.yaml
To be aligned with conda-forge : https://github.com/conda-forge/cppad-feedstock/pull/15 .
=> Bump cppad version to 20220000.3

releases/latest.releases.yaml
Fix the problems described in https://github.com/robotology/robotology-superbuild/pull/1115#issuecomment-1129254994 . Thanks @S-Dafarra for the tags.
=> Add tags for yarp-device-openxrheadset and yarp-openvr-trackers

releases/latest.releases.yaml
=> Update latest.releases.yaml to `icub-firmware-models@v1.25.0`

releases/2022.05.2.yaml
=> Update 2022.05.2.yaml w/ `icub-main@v1.16.0`

releases/2022.05.2.yaml
YARP updated to v3.7.2.
See https://github.com/robotology/yarp/releases/tag/v3.7.2.
=> Use `YARP-3.7.2`

cmake/BuildICUB.cmake
It fixes #1223 
cc @triccyx @pattacini
=> Add embObjBattery to BuildICUB.cmake for icub head profile

cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt, releases/2022.08.1.yaml
@pattacini please bump the versions you want to bump in the 2022.08.1.yaml file. When we are ready we can merge and release.
=> Add release 2022.08.1 

releases/2022.08.1.yaml
From https://github.com/robotology/robotology-superbuild/pull/1260 .
=> Add 2022.08.1.yaml

CHANGELOG.md, cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt, releases/2022.02.2.yaml
As discussed in https://github.com/robotology/robotology-superbuild/pull/1283#issuecomment-1268553417 , @hypothe let me know if this is ok for you.
=> Release version 2022.02.2 

CHANGELOG.md, cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt, releases/2022.09.1.yaml
The PR is ready, we just need to bump the tag in 2022.09.1 and then we should be ready for release.
=> Prepare for 2022.09.1 release

releases/latest.releases.yaml
=> Update latest release of `icub-firmware-models`

.github/workflows/build-docker-images.yml
this PR contains the following changes:
- renamed the workflow `icubTechIIT_code.yml` in `build-docker-images.yml` 
- updated the repo of the repository dispatch action
- updated the git hub secrets.
cc @pattacini
=> Updated the workflow for building docker images on release

.github/workflows/ci.yml
Workaround for https://github.com/robotology/robotology-superbuild/issues/1353 .
=> Add workaround for GitHub Actions failure tcl-tk brew upgrade

releases/latest.releases.yaml
=> Update `find-superquadric` latest release

.github/workflows/ci.yml, doc/conda-forge.md
Remove workarounds added in:
* https://github.com/robotology/robotology-superbuild/pull/1329
* https://github.com/robotology/robotology-superbuild/pull/1367
As the related problems were solved.
=> Remove hard pins on CMake and OpenCV in conda-forge

cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt, releases/2023.02.2.yaml
Create yaml file for release 2023,02.2
=> Release 2023.02.2

releases/2023.02.1.yaml, releases/2023.02.2.yaml
From:
* https://raw.githubusercontent.com/robotology/robotology-superbuild/releases/2023.02/releases/2023.02.1.yaml
* https://raw.githubusercontent.com/robotology/robotology-superbuild/releases/2023.02/releases/2023.02.2.yaml
=> Add 2023.02.1.yaml and 2023.02.2.yaml files

cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt
=> Prepare 2023.02.3 part 2

cmake/BuildICUB.cmake
=> embObjStrain removal

cmake/Buildmujoco-simulink-blockset.cmake, cmake/ProjectsTagsStable.cmake, cmake/ProjectsTagsUnstable.cmake, conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake, releases/latest.releases.yaml
Fix https://github.com/robotology/robotology-superbuild/issues/1434 .
Test build: https://github.com/robotology/robotology-superbuild/actions/runs/5452128660 .
=> Fix build of mujoco-simulink-blockset conda package

cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt, releases/2023.05.1.yaml
=> Prepare for 2023.05.1

cmake/Fetchonnxruntimebinaries.cmake
Without this, the compilation failed on ergocub-torso
=> Add include fetchcontent in Fetchonnxruntimebinaries.cmake

scripts/robotologyUpdateLatestReleases.sh
Fix https://github.com/robotology/robotology-superbuild/issues/1469 .
=> Add proxsuite to the list of projects are updated manuaally in the update latest release script

.github/dependabot.yml, .github/workflows/ci.yml
Fix regression in https://github.com/robotology/robotology-superbuild/pull/1481 .
=> Use actions/checkout@v3.6.0 in bionic CI build for Bionic compatibility

.github/workflows/generate-conda-packages.yaml
Fix https://github.com/ami-iit/robot-log-visualizer/issues/60 . Fix regression caused by https://github.com/robotology/robotology-superbuild/pull/1243 .
=> generate-conda-packages: Fix upload of noarch packages

.github/workflows/ci.yml, cmake/Buildrobot-log-visualizer.cmake, doc/conda-forge.md
Fix https://github.com/ami-iit/robot-log-visualizer/issues/67 .
=> Add gst-plugins-good and gst-plugins-bad conda packags as depedencies of robot-log-visualizer

.github/workflows/ci.yml, doc/conda-forge.md
Workaround for https://github.com/robotology/robotology-superbuild/issues/1537 .
=> Pin graphviz to 8

cmake/Buildbipedal-locomotion-framework.cmake
=> Fix python bindings installation folder for bipedal-locomotion-framework

.github/workflows/matlab-one-line-install-test.yml
Check if https://github.com/matlab-actions/run-command/issues/43 is solved.
=> matlab-one-line-install-test: Use also latest matlab_version and use v2 version of matlab actions

cmake/Buildcasadi.cmake, cmake/ProjectsTagsStable.cmake, cmake/ProjectsTagsUnstable.cmake, releases/latest.releases.yaml
Bump CasADi to 3.6.5, latest release.
=> Bump CasADi to 3.6.5

cmake/Buildyarp-device-keyboard-joypad.cmake
Fix https://github.com/robotology/robotology-superbuild/issues/1645 .
=> Add conda dependencies for yarp-device-keyboard-joypad

doc/faqs.md, scripts/install_robotology_packages.m
See https://github.com/ami-iit/matlab-whole-body-simulator/discussions/92#discussioncomment-9603906 .
=> The KMP_DUPLICATE_LIB_OK problem is present also on Windows so document and apply the workaround also on Windows

doc/cmake-options.md
This fixes the python snippet that needs to be added on windows bindings builds.
=> Fix python dll snippet

cmake/RobotologySuperbuildOptions.cmake, conda/cmake/CondaGenerationOptions.cmake, packaging/windows/CMakeLists.txt, releases/2024.11.1.yaml
A quick patch release to increase the ergocub-software version to 0.7.6 .
=> [2024.11] Bump some repos to new versions and release v2024.11.1

conda/multisheller/blockfactory_activate.msh, conda/multisheller/blocktest_activate.msh, conda/multisheller/casadi-matlab-bindings_activate.msh, conda/multisheller/gazebo-yarp-plugins_activate.msh, conda/multisheller/gazebo-yarp-plugins_deactivate.msh, conda/multisheller/human-dynamics-estimation_activate.msh, conda/multisheller/human-dynamics-estimation_deactivate.msh, conda/multisheller/human-gazebo_activate.msh, conda/multisheller/icub-contrib-common_activate.msh, conda/multisheller/icub-main_activate.msh, conda/multisheller/icub-main_deactivate.msh, conda/multisheller/idyntree-matlab-bindings_activate.msh, conda/multisheller/matlab-whole-body-simulator_activate.msh, conda/multisheller/mujoco-simulink-blockset_activate.msh, conda/multisheller/osqp-matlab_activate.msh, conda/multisheller/wb-toolbox_activate.msh, conda/multisheller/whole-body-controllers_activate.msh, conda/multisheller/yarp-matlab-bindings_activate.msh, conda/multisheller/yarp_activate.msh, conda/multisheller/yarp_deactivate.msh
Fix https://github.com/robotology/robotology-superbuild/issues/1497 .
=> Cleanup unused multisheller script and prepend variables instead of appending

cmake/Buildsimulink-arsenal.cmake, cmake/RobotologySuperbuildLogic.cmake, releases/latest.releases.yaml
Hi @traversaro, @Nicogene 
This PR proposes to add [Simulink Arsenal](https://github.com/icub-tech-iit/simulink-arsenal) to the ecosystem as this library provides components that may/will be integrated in `icub-firmware-models`.
No need to build it.
cc @mfussi66
=> Simulink Arsenal
