CMakeLists.txt
README.md
cmake/ConfigureFileWithCMakeIf.cmake
cmake/template/setup.sh.in

This PR adds a basic support for generating a `setup.sh` file to set all the the environmental variables necessary to run all the robotology-superbuild software, to streamline installation of an existing superbuild. 
The main difference with respect to catkin/ament style `setup.sh` is that:
* All the environmental variables are still extensively documented in the superbuild documentation, and the expert user may chose to set them manually (or only set a subset of them). The `setup.sh` is just a convenient feature, but it should not be a black box in which an arbitrary number of enviroment variables are set. 
* While in catkin/ament the environmental variables are set by the subprojects via hooks, the idea here is that the superbuild maintainer is responsible to manage which environmental …

Add support for setup.sh and expand Gazebo documentation

---

CMakeLists.txt
README.md

In particular, the PYTHON and LUA options still need proper documentation, so they have been hidden and some issue have been opened to document them: 
* https://github.com/robotology/robotology-superbuild/issues/30
* https://github.com/robotology/robotology-superbuild/issues/28
We are also missing a few "Check your installation" sections, see:
* https://github.com/robotology/robotology-superbuild/issues/32
* https://github.com/robotology/robotology-superbuild/issues/29

Finalize the README removing all the TODOs

---

README.md

@lucaTagliapietra using this procedure, I was able to compile the superbuild on the workstation your provided me. 
Fix https://github.com/robotology/robotology-superbuild/issues/42 .

Document how to use vcpkg to install dependencies for the superbuild

---

.travis.yml
README.md

libcv-dev libhighgui-dev libcvaux-dev have been legacy packages substituted by libopencv-dev for a long time (i.e. libopencv-dev is a package available also on old distributions). 
See https://github.com/robotology/robotology-superbuild/issues/56 .

Cleanup installation instructions for Ubuntu 18.04

---

cmake/BuildICUB.cmake
cmake/BuildYARP.cmake

Enabled some options that are necessary to use the superbuild on iCub's head,
see https://github.com/robotology/robotology-superbuild/issues/88#issuecomment-397646254 .
Furthermore, remove some options that were hardcoded to OFF: not mentioning them
leave to the users the freedom to eventually set them to ON if they need them.

Cleanup YARP and ICUB cmake options

---

.travis.yml

This is necessary after the release of iDynTree 0.10 that requires at least GCC 5

[travis] Use GCC 5

---

README.md
cmake/ProjectsTagsMaster.cmake
cmake/template/startup_robotology_superbuild.m.in

The toolbox's directory name inside `share/` was recently changed and the documentation needed to be updated accordingly. Furthermore, the tag has been bumped for including the latest bugfixes.
In order to avoid breaking controllers after https://github.com/robotology/wb-toolbox/pull/147, the tag in `master` points to the commit https://github.com/robotology/wb-toolbox/commit/0ff5ca4aecc607e1f1901abffe3b7c960a4e6b11.
Refer to https://github.com/robotology/wb-toolbox/pull/148.

Updated WB-Toolbox informations

---

cmake/ProjectsTagsMaster.cmake

Now the `master` branch of Whole Body Toolbox is aligned with the other robotology repositories.

Updated WBToolbox tag in ProjectsTagsMaster.cmake

---

.ci/install_debian.sh
README.md

libxml2 is now required by iDynTree, since release 0.11.
See https://github.com/robotology/QA/issues/316 for more info.

Add libxml2 dependency to docs and CI

---

cmake/BuildWBToolbox.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/120 and https://github.com/robotology/robotology-superbuild/issues/44 .

Update BuildWBToolbox with the current dependencies

---

README.md

Given https://github.com/robotology/robotology-superbuild/issues/134 , I think it make sense to do this, at least until https://github.com/robotology/robotology-superbuild/issues/134 is fixed.
cc @kouroshD

Remove instruction on using dependencies from vcpkg on Windows

---

README.md

@traversaro As we discussed in #151 I have updated the mentioned section of the readme in this PR:
- Increase the readability of configuring the Winodows: Configure your environment similar to the ones of Linux and MacOS.
- There was a typo on  `ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX = $ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX/build/install`, which is fixed, also `$` and `/` are changed to `%VARIABLE NAME%` and `\`.
- I have added a note `Important` at the end of Configuration section to respond [this comment](https://github.com/loc2/lab-events-demos/issues/62#issuecomment-449487202), so that the users can benefit from dependency walker to check if there are dependency problem, I have not mentioned the sophos antivirus problem directly.
-

Updated ReadMe for Winodows: Configure your environment

---

cmake/BuildYARP.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/164

Enable YARP_USE_I2C in YARP when ROBOTOLOGY_ENABLE_ICUB_ROBOT is true

---

README.md

Furthermore, remove documentation about ancient systems that are not supported.

Explicitly reference to YARP documentation to specify supported systems

---

README.md

I think the chance of confusion are relatively limited now. What do you think @liesrock ?

Remove readme warning related to the "old" robotology-superbuild

---

CMakeLists.txt
README.md
cmake/BuildICUB.cmake
cmake/BuildYARP.cmake
cmake/Buildrobots-configuration.cmake
cmake/Buildxsensmt-yarp-driver.cmake

This PR contains several commits related to the cleanup of the part of the superbuild used to automatize the setup of iCub software on the head of the iCub robot. It consolidates a few commits (sorry) to avoid overloading the CI infrastructure. .
Details explanation is present in each commit: 
* https://github.com/robotology/robotology-superbuild/commit/9cbfd6528bb7181e86e3560eec654e4af046c8d3 :  Renamed ROBOTOLOGY_ENABLE_ICUB_ROBOT_ETH and ROBOTOLOGY_ENABLE_ICUB_ROBOT_CAN options to ROBOTOLOGY_ENABLE_ICUB_HEAD e ROBOTOLOGY_USES_CFW2CAN
* https://github.com/robotology/robotology-superbuild/commit/bf65022af7bf7568121794e0be8ba485a0bf4968 : Make sure that robots-configurations installs fine on system without YARP_ROBOT_NAME defined as an enviroment variable 
* …

Cleanup related to run the superbuild inside the pc104/icub-head system

---

cmake/IncludeUrl.cmake

IncludeUrl.cmake is a file vendored  to permit to bootstrap YCM, so it needs to be updated whenever it is changed in YCM (see http://robotology.github.io/ycm/gh-pages/v0.10/manual/ycm-using.7.html#using-ycm-as-soft-dependency). 
Get version from commit https://github.com/robotology/ycm/commit/3dcadbd146ad5c0cdba7034c696bc73b11b4a5a0,
released as part of YCM 0.10 .
Solve the warning mentioned in https://github.com/robotology/robotology-superbuild/issues/191

Update YCM's IncludeUrl.cmake to latest version

---

.travis.yml

As discussed in https://github.com/robotology/robotology-superbuild/pull/196#issuecomment-479784237 .

[travis] Drop compilation on clang on Linux

---

CMakeLists.txt

The exact version if  using the bootstrapped YCM, or at least that version when using system's YCM
Fix https://github.com/robotology/robotology-superbuild/issues/21 
Fix https://github.com/robotology/robotology-superbuild/issues/189
Fix https://github.com/robotology/robotology-superbuild/issues/191

Use v0.10.2 of YCM

---

cmake/BuildICUB.cmake

As emerged during the tests on iCubGenova01 ( see https://github.com/robotology/robotology-superbuild/pull/212 ).

Add missing ICUB_HEAD profile options in the BuildICUB script

---

cmake/BuildYARP.cmake

This was detected by @pattacini when testing face expressions on the `iCubGenova01` "Blacky" robot. This matches indeed the documentation present in http://wiki.icub.org/wiki/Compilation_on_the_pc104 . In that page, regarding YARP also the `serial` device was enabled, but apparently the `serial` device is a builtin device of YARP (https://github.com/robotology/yarp/blob/v3.1.2/src/libYARP_dev/src/devices/ServerSerial/ServerSerial.cpp#L17) so there is no need to explicitly enable it (probably this changed at some point in the past). Furthermore, also the `portaudio` device  is enabled, but I do not see it used anywhere in https://github.com/robotology/robots-configuration/search?q=portaudio&unscoped_q=portaudio, so I guess that device is not actually required.

If ICUB_HEAD profile is enabled enable serialport device in YARP

---

cmake/BuildYARP.cmake

For some reason the Lua bindings were not enabled in YARP.

Correctly handle ROBOTOLOGY_USES_LUA in BuildYARP.cmake

---

cmake/BuildiDynTree.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/221 .
The usual problems related to the use of `CMAKE_ARGS` discussed in https://github.com/robotology/robotology-superbuild/issues/68 apply.

Set IDYNTREE_USES_IPOPT to ON in BuildiDynTree

---

CMakeLists.txt

Without this change, YARP downloads its own version of YCM, as 0.10.2 is not recent enough for YARP.

Bump YCM bootstrapped version to latest released version v0.10.4

---

README.md

Travis is basically broken almost all the time, so it is easier to just start migrating the README to use GitHub Actions badge

Switch to use GitHub Actions badge in README

---

README.md

Fix https://github.com/robotology/robotology-superbuild/issues/146 .
@AlbertoRemusIIT especially the "sanitize the enviromental variable" is quite important if you install the robotology-superbuild on both Windows and WSL.

Add documentation on using the superbuild on Windows Subsystem for Linux (WSL)

---

cmake/BuildICUB.cmake

Workaround for https://github.com/robotology/icub-main/issues/606 , as discussed in https://github.com/robotology/icub-main/issues/604 .

Set ICUB_USE_GTK2 to OFF in icub-main

---

cmake/BuildICUB.cmake

Sets ICUB_USE_icub_firmware_shared to ON from ROBOTOLOGY_ENABLE_ICUB_HEAD for compiling the usual tools `canLoader, ethLoader, FirmwareUpdater, strainCalib, strainCalibrationDataAcquisition`.
Fixes https://github.com/robotology/robotology-superbuild/issues/281.

Set ICUB_USE_icub_firmware_shared to ON for compiling CAN/ETH tools

---

cmake/Buildwalking-controllers.cmake

In https://github.com/robotology/walking-controllers/pull/44 the `ICUBcontrib` CMake package was added to the walking-controllers dependencies, but we never updated the related file in the superbuild.

Add ICUBcontrib to walking-controllers dependencies

---

cmake/BuildRobotTestingFramework.cmake

Unfortunately RTF does not support Python3, so it is better to just remove python support for it from the superbuild: https://github.com/robotology/robot-testing-framework/issues/37 .
This is a first step towards supporting macOS ( https://github.com/robotology/robotology-superbuild/issues/289 ) and Ubuntu 20.04 (that will use Python 3 by default).

Always disable Python bindings of robot-testing-framework

---

README.md
doc/use-on-icub-head.md

Basically I am just moving some info from https://github.com/robotology/robotology-superbuild/issues/88 to a more permanent location. 
Note that this is not meant to be a duplicate of  the information provided in the iCub wiki, as iCub wiki pages to describe the installation with the superbuild are already provided, and are also linked in the new document.

Create some documentation related to use the robotology-superbuild on the icub-head/pc104

---

.github/workflows/ci.yml

In particular, add `qt5-declarative`, `qt5-multimedia` and `qt5-quickcontrols2` by using https://github.com/robotology-playground/robotology-superbuild-dependencies/releases/tag/0.0.2 .

Windows CI: Add  missing qt5 ports to vcpkg dependencies

---

.ci/install_debian.sh
README.md
cmake/BuildYARP.cmake

With this PR the `usbCamera yarp device` is compiled if `icub-head profile` is active.
Since some robots mount usb cameras, it is important to make the corresponding device available.
To achieve this, I changed the cmake file ```cmake/BuildYARP.cmake ``` enabling the usbCamera cmake option only on Linux system.
Moreover I updated the installation instructions for Linux system by adding `libv4l-dev` library, because `usbCamera`is based on `video4linux library`.
I verified the `usbCamera` device is available using `yarpdev --list` command. I think this check besides CI tests, could be sufficient to verify that these changes could be ok.

Added USB camera yarp device in icub-head profile

---

.github/workflows/ci.yml

This is required by : https://github.blog/changelog/2019-10-31-github-actions-macos-virtual-environment-is-updating-to-catalina-and-dropping-mojave-support/ .

GitHub Actions: migrate from macOS-10.14 to macOS-latest

---

README.md
doc/environment-variables-configuration.md

As discussed in https://github.com/robotology/robotology-superbuild/issues/161, this PR moves the environment variables detailed documentation to a separate document, simplifying the main README. 
Fix https://github.com/robotology/robotology-superbuild/issues/161 
Fix https://github.com/robotology/robotology-superbuild/issues/147 ,  by documenting `addPathsToEnvVariables.ps1` and `removePathsFromEnvVariables.ps1` scripts.

Cleanup README moving most details on enviroment variables to a separete document

---

CMakeLists.txt
README.md

Following the announcement in https://github.com/robotology/QA/issues/364 and the discussion  in  https://github.com/robotology/ycm/issues/261 ,  we require CMake 3.12 now . This PR updates the documentation, indicating the recommended way to install a recent CMake in Debian 9 and Ubuntu 18.04 .

Update installations docs to mention that CMake 3.12 is required and require it at CMake level

---

cmake/BuildYARP.cmake

This removes some CMake warnings when YARP is configured. 
Fix https://github.com/robotology/robotology-superbuild/issues/218 .

Update names of YARP CMake options

---

CMakeLists.txt

Despite what was written in the PR description of https://github.com/robotology/robotology-superbuild/pull/303, by default the `ROBOT_TESTING` component was set enabled. As discussed in  https://github.com/robotology/robotology-superbuild/pull/303, however, most users do not need RTF and icub-tests, and disabling them also reduce the chance of users experiencing https://github.com/robotology/robotology-superbuild/issues/215 .

Set ROBOTOLOGY_ENABLE_ROBOT_TESTING default value to OFF

---

.github/workflows/ci.yml

Attempt to fix GitHub Actions compilation with a workaround for https://github.com/actions/virtual-environments/issues/10 .
Without this fix, the GitHub Action jobs are failing, see https://github.com/robotology/robotology-superbuild/commit/9d8587921d79540c50fa98a906738a350179618a/checks?check_suite_id=405495333 .

GitHub Actions: force use of system-installed boost

---

packaging/windows/CMakeLists.txt
packaging/windows/README.md
packaging/windows/scripts/addPathsToUserEnvVariables-vcpkg.ps1
packaging/windows/scripts/addPathsToUserEnvVariables.ps1
packaging/windows/scripts/removePathsFromUserEnvVariables-vcpkg.ps1
packaging/windows/scripts/removePathsFromUserEnvVariables.ps1
packaging/windows/scripts/setup-vcpkg.bat
packaging/windows/scripts/setup.bat
packaging/windows/scripts/update-env-variables.qs.in

This PR adds a script that uses [CPack](https://cmake.org/cmake/help/v3.12/module/CPack.html), [Qt Installer Framework](https://doc.qt.io/qtinstallerframework/index.html) and [vcpkg](https://github.com/microsoft/vcpkg)-provided dependencies to  generate a self-contained executable for the software contained in the robotology-superbuild. 
The limitations are currently the following: 
* Support only for 64-bit shared binaries, i.e. `x64-windows` 
* Due to the fact that several software in the robotology-superbuild are not relocatable, only support installation in `C:\robotology` prefix. 
* All the software needs to be installed, it is not possible to manually select which sofware to install. 
With some work, it will be possible to remove some of this limitations in the future. However, I …

Add scripts for generating Windows installers

---

.github/workflows/ci.yml

As a workaround for https://github.com/robotology/robotology-superbuild/issues/339 and fix the CI, so we can test other PRs while https://github.com/robotology/robotology-superbuild/issues/339 is being fixed.

Disable Human Dynamics profile on Windows

---

cmake/YCMLoadVcsYamlInfo.cmake

This function permits to load the `<package>_TAG` and `<package>_REPOSITORY` variables from a YAML file.
In particular, the YAML format used is the one produced and consumed by the [`vcstool`](https://github.com/dirk-thomas/vcstool) command line tool, that is used in ROS2 tutorials to manage groups of repositories. 
For example, the existing  file `ProjectsTagsStable.cmake` (see https://github.com/robotology/robotology-superbuild/blob/34325b12084672d1869695366ca53bb4ffe83a7f/cmake/ProjectsTagsStable.cmake) file could be refactored in:
~~~cmake
include(YCMLoadVcsYamlInfo)
ycm_load_vcs_yaml_info(YAML_FILE project_tags_stable.repos)
~~~ 
With `project_tags_stable.repos` being: 
~~~yaml
repositories:
osqp:
type: git
url: https://github.com/oxfordcontrol/osqp.git
version: v0.6.0
YARP:
type: …

Add ycm_load_vcs_yaml_info CMake function

---

CMakeLists.txt

This may require that `cmake` is executed as `sudo` if `YCM_EP_INSTALL_DIR` points to `/usr/local`, but in any case the use of `YCM_EP_INSTALL_DIR` is an experimental feature reserved only to advanced setups, so I do not think it is a big problem.

Configure setup scripts directly in YCM_EP_INSTALL_DIR instead of hardcoding ${CMAKE_BINARY_DIR}/install

---

.github/workflows/ci.yml

Due to the nature of robotology-superbuild, often the unstable branches build fails. However, it is important that even if the unstable branches build fails the stable branches build continue to build, so we are still able to detect regressions on the stable branches, and  just merge PRs if the stable branches pass.

Disable fail-fast in GitHub Actions

---

cmake/Buildrobots-configuration.cmake

To solve problems such as https://github.com/robotology/robotology-superbuild/issues/223, it is easier to always install all the robot configuration files. If this creates problems on systems such as pc104, we can always go back.
Fix https://github.com/robotology/robotology-superbuild/issues/223 .

Install all robot configuration files regardless of YARP_ROBOT_NAME

---

README.md
doc/vcpkg-dependencies.md

As https://github.com/robotology/robotology-superbuild/issues/134 has been fixed, we can finally avoid to install 4 different installers to install the superbuild dependencies on Windows, and we can just rely on `vcpkg`, relying in particular on the pre-compiled version available at https://github.com/robotology-playground/robotology-superbuild-dependencies-vcpkg to avoid the need of compiling all the libraries for hours.

Document installation of Windows dependencies via vcpkg

---

.github/workflows/ci.yml

This is required to be compatible with the installer scripts provided in https://github.com/robotology/robotology-superbuild/pull/334 .
Other related issue: https://github.com/robotology-playground/robotology-superbuild-dependencies-vcpkg/pull/5 .

Use version 0.0.3 of the pre-compiled vcpkg workspace in CI

---

CMakeLists.txt

This commits hardcodes the ROBOTOLOGY_PROJECT_TAGS_CUSTOM_FILE to point to the  2020.02.yaml file for the `releases/2020.02` branch. The idea  is to tag the `v2020.02` tag on this branch (and eventually other patch releases of the v2020.02 series), to ensure that a user of the superbuild just needs to checkout the correct tag of the superbuild, and then the superbuild will download the correct versions of the subprojects. 
Note that is quite important to **never forward merge** the `releases/**` branches to `master`.

Hardcode the ROBOTOLOGY_PROJECT_TAGS_CUSTOM_FILE to 2020.02.yaml for the releases/2020.02 branch

---

releases/2020.02.yaml

Version bumped in https://github.com/robotology/robotology-superbuild/pull/352 .

Backport latest version updated for 2020.02

---

CMakeLists.txt

YCM v0.11.1 ( https://github.com/robotology/ycm/releases/tag/v0.11.1 ) contains some critical bug-fixes, so it is good to require and to use them.

Boostrap and require recent YCM v0.11.1 in the superbuild

---

cmake/ProjectsTagsUnstable.cmake

This is a workaround for  https://github.com/robotology/robotology-superbuild/issues/372

Use fixed ICUB and icub-firmware-shared commits

---

CMakeLists.txt
cmake/ProjectsTagsStable.cmake

For historical reason, `YCM_TAG` was hard-coded and it was not possible to change it as  for the rest of the projects, this PR fixes this. 
Fix https://github.com/robotology/robotology-superbuild/issues/283

Do not consider YCM_TAG differently from the rest of <package>_TAG options

---

README.md

It is only necessary to specify that the default CMake is enough.
I also removed the info that CMake in stretch-backports is 3.13, as it has been updated instead to 3.16 .

Add support for Ubuntu 20.04 in README

---

.github/workflows/ci.yml
releases/2020.02.yaml
releases/2020.05.yaml

* Add file containing versions of projects for 2020.05 release  (for now just a copy of 2020.02's tags, with just the change of whole-body-estimators and  the removal of codyco-modules and deps to account for https://github.com/robotology/robotology-superbuild/pull/374)
* Add support for testing in CI a release (2020.05 for now) and also test the default `ROBOTOLOGY_PROJECT_TAGS` setting instead of hardcode `Stable` (so we actually test correctly the `releases/**` branches

Add preliminary support for 2020.05 release

---

README.md

See https://github.com/robotology/robotology-superbuild/issues/139 for a detailed explanation.

Document that ROBOTOLOGY_USES_OCTAVE is not supported on Windows

---

README.md

Fix https://github.com/robotology/robotology-superbuild/issues/236 .
If one of the main users of the `ROBOTOLOGY_ENABLE_ICUB_HEAD` option wants to check this text (such as @valegagge @davidetome @julijenv @marcoaccame @kouroshD @Yeshasvitvs @lrapetti @claudia-lat ) would want to check this docs, it would be great!

Add documentation on using the ROBOTOLOGY_ENABLE_ICUB_HEAD on Windows  and macOS

---

CMakeLists.txt

The `install` target of the superbuild is not supported for several reason, and users that want to install their project in a specific directory can use  the existing YCM variable YCM_EP_INSTALL_DIR  (see https://github.com/robotology/ycm/pull/289 ).
However, to avoid that some user that does not read the docs runs the install target, let's disable it. 
Fix https://github.com/robotology/robotology-superbuild/issues/356 .

 Disable YCM-created install target

---

README.md

In particular remove all the references to the FT shoes, as the esdcan option and driver can be used also by users that do not use the FT shoes at all. 
Fix https://github.com/robotology/robotology-superbuild/issues/235 .

Cleanup documentation relative to the ROBOTOLOGY_USES_ESDCAN

---

CMakeLists.txt

During the past years, we experienced quite a lot of times that for some reason on a setup 
the superbuild was finding its own installed packages, or finding the one of a similar superbuild 
installed on another setup. As recovering from this kind of errors is tricky for users, and as 
most of robotology-superbuild users do not need to find  the packages installed by the superbuild in  their system, the YCM_DISABLE_SYSTEM_PACKAGES option was introduced in YCM 
( see https://github.com/robotology/ycm/pull/332 )  to disable the use of  any system installed package if the same package can be installed by the superbuild (equivalent of setting  all the USE_SYSTEM_<project> options to OFF). 
This option is set by default to `OFF` on YCM for backward compatibility, but to avoid all the problems …

Set YCM option YCM_DISABLE_SYSTEM_PACKAGES to ON

---

.github/workflows/ci.yml

As we recently have added in  our GitHub Actions script: 
* Builds using the latest Debian stable and Ubuntu 20.04 ( https://github.com/RobotLocomotion/drake/issues/13173 ) 
* Builds against the candidate tags for the next release ( https://github.com/robotology/robotology-superbuild/pull/386 )
the number of jobs  has grown a lot. To decrease the number of jobs, I think it is safe to remove the Debug jobs for Ubuntu 18.04, macOS and Windows. The amount of failures that affect only Debug jobs and not Release jobs is quite limited (typically just some code that was not updated in a `ifndef NDEBUG` or in an `assert`), and we still use the Debug build mode in Docker builds.

[CI] Remove Debug builds on Ubuntu 18.04, macOS and Windows

---

.github/workflows/ci.yml

To avoid duplication, we reuse most of the existing logic of the Windows CI, the only modifications  are: 
* We always set (in Windows) the `-DYCM_EP_INSTALL_DIR=C:/robotology/robotology`, to match what we will use in the installer generation 
* For builds associated to a release event, we also build the superbuild in Debug mode, so that the Debug libraries are included in the installer 
* We generate the installer using the instructions added in https://github.com/robotology/robotology-superbuild/pull/334
* We then use the [`actions/upload-release-asset`](https://github.com/actions/upload-release-asset) Action to upload the generated installer to the Release page (I added a `ACCESS_TOKEN` Secret to the repo containing an appropriate token) 
Fix …

Add generation and upload of Windows installer in GitHub Actions script

---

packaging/windows/scripts/setup-vcpkg.bat

The correct name of triplet in vcpkg is x64-windows, not windows-x64 .

Fix setup-vcpkg.bat

---

.github/workflows/ci.yml
releases/2020.05.yaml

Using the Gazebo binaries produced in https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/17 .

Enable ROBOTOLOGY_USES_GAZEBO option on Windows CI

---

README.md

As compilation is working correctly as seen in https://github.com/robotology/robotology-superbuild/pull/406, I think we can document this option.

Document ROBOTOLOGY_USES_GAZEBO option on Windows

---

.github/workflows/ci.yml
README.md
cmake/BuildiDynTree.cmake

Before this fix, whetever iDynTree was compiled or not with OsqpEigen support was non 
deterministic, and based on wheter OsqpEigen  was already compiled and  installed when
iDynTree was configured. With  this fix, the dependency of iDynTree on OsqpEigen is explicitly 
indicated, and the IDYNTREE_USES_* options are explicity set, so that if for some reason one
of the dependency is not installed correctly, iDynTree configuration will fail.
Also add Add fail-fast: false also to Docker-based GitHub Actions jobs, that had the nice side effect: of helping in debug the problems discussed in https://github.com/robotology/osqp-eigen/pull/62 .

 Add missing dependencies of iDynTree on OsqpEigen 

---

.ci/install_debian.sh
README.md

Apparently on a vanilla Ubuntu 20.04, not having  this  dependency create runtime problems for iCub_SIM .
Thanks @pattacini

Add missing freeglut3-dev dependency

---

.github/workflows/ci.yml

Using the latest version make sense in general (it is the version that new users will install by default) and will also help as a workaround against https://github.com/osrf/homebrew-simulation/issues/1022 .

GitHub Actions: Use gazebo11 on macOS

---

.github/workflows/ci.yml
releases/2020.08.yaml

It contains the tag as released in 2020.05, with some projects bumped to use thee branches on which the release contained in 2020.08 will be tagged.
See https://github.com/robotology/robotology-superbuild/blob/master/doc/developers-faqs.md#how-to-do-a-new-release for more details.

Create 2020.08.yaml for 2020.08 release

---

doc/vcpkg-dependencies.md

Align the list of dependencies with https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/23 and https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/24 . I also aligned the list w.r.t. boost ports, that for some reasons they were not aligned.

Document vcpkg dependencies on several boost ports, glew glfw3 and portaudio

---

.ci/install_debian.sh

Python 2 is EOL since 1st of January 2020 and some projects removed support for it, so let's use Python 3 for testing.
Fix https://github.com/robotology/robotology-superbuild/issues/432 .
Related issue: https://github.com/robotology/robotology-superbuild/issues/28 .
The Windows CI jobs will probably still fail due to https://github.com/robotology/robotology-superbuild/issues/429 , so the important thing for this PR is to check that all Linux jobs succeed .

On Debian/Ubuntu CI use python3-dev package

---

.github/workflows/ci.yml

Workaround for https://github.com/robotology/robotology-superbuild/issues/429

GitHub Actions: Disable Git symlinks on Windows

---

releases/2020.02.yaml
releases/2020.05.yaml
releases/2020.08.yaml

The PRs https://github.com/robotology/robotology-superbuild/pull/438 and https://github.com/robotology/robotology-superbuild/pull/437 changed the name of some superbuild subprojects `icub_firmware_shared` and `blocktestcore`, but as part of those PR the `yml` releases files were not updated, and so the wrong version of those dependencies was used. 
Fix https://github.com/robotology/robotology-superbuild/issues/441 .

Propagate name update of icub_firmware_shared and blocktest core to release .yml files

---

packaging/windows/CMakeLists.txt

This is version number that needs to be updated manually is extremely error prone.

Bump installer version to 2020.08

---

.github/workflows/ci.yml

This is useful to monitor regressions due to missing disk space, see for example https://github.com/robotology/robotology-superbuild/issues/456 .

GitHub Actions: Add check on free space

---

README.md

For example, right now it points to the 0.3.0 version, which is not the latest. This would avoid us to update this README every time we have a new release.

Update README to point to the latest version of robotology-superbuild-dependencies-vcpkg

---

.ci/install_debian.sh

This is now required since https://github.com/robotology/idyntree/pull/726 .
Without this fix, the unstable CI is failing with the error: 
~~~
2020-09-01T14:03:36.5315042Z CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
2020-09-01T14:03:36.5315306Z   Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found
2020-09-01T14:03:36.5315430Z   version "3.8.2")
2020-09-01T14:03:36.5315536Z Call Stack (most recent call first):
2020-09-01T14:03:36.5315828Z   /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
2020-09-01T14:03:36.5316211Z   /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
2020-09-01T14:03:36.5316487Z …

GitHub Actions: install python3-numpy

---

.github/workflows/ci.yml

This should mitigate problems due to low space available in CI machine such as the one reported in https://github.com/robotology/robotology-superbuild/issues/456 .

GitHub Action: remove build directories on Windows

---

.github/workflows/ci.yml

This fixes the same problem as https://github.com/robotology/robotology-superbuild/pull/458 but for Debian Stable.

GitHub Actions: Switch Debian stable testing to use backports

---

README.md

Fix https://github.com/robotology/robotology-superbuild/issues/462 . I do not bump the `cmake_minimum_required`  as the problem will not emerge until the new version of iDynTree is released, so for now just documenting it I think it is enough.

Document requirement of CMake 3.16

---

.ci/install_debian.sh
.github/workflows/ci.yml
README.md
cmake/BuildYARP.cmake
doc/vcpkg-dependencies.md

The `mjpeg` carrier is used in the Oculus driver, and in general it is a small component with limited dependencies (just libjpeg that is already installed in almost all systems), so I think it make sense to enable it.
Similarly, also the `portmonitor`, `depthimage` and `depthimage2` carriers are also minimal components that is convenient to enable to simplify the use of depth image related functionalities.

YARP: Set ENABLE_yarpcar_mjpeg, ENABLE_yarpcar_portmonitor, ENABLE_yarpcar_depthimage and ENABLE_yarpcar_depthimage2 to ON by default

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

Due to https://github.com/robotology/robotology-superbuild/issues/469, the robotology-superbuild on both Stable and Unstable branches is broken on Linux and macOs . As a temporary solution until https://github.com/robotology/yarp/pull/2356 is merged, let's pin YARP to some working commits.

Temporary pin YARP stable and unstable version to a valid commit

---

.github/workflows/ci.yml

This should permit to early catch compilation problems due to new version of Debian packages, before they end in a Ubuntu LTS release.
In particular, let's see if https://github.com/robotology/robotology-superbuild/issues/383 is now solved.

Enable Debian Sid testing in CI

---

.github/workflows/ci.yml

See https://github.com/robotology/robotology-superbuild/issues/477 for more details. For now, only Linux is added, because some dependencies are still missing on macOS (freeglut) and Windows (ipopt).
In a nutshell conda is a package manager (originally for Python, but now quite language agnostic) that works on Linux, macOS and Windows. `conda-forge`  is a channel for the conda package manager that provides many dependency, in particular all the one that are required by the robotology-superbuild .
The use of conda is complementary to the compilation modes that we already use and are not substituted by conda, but its advantages are: 
* Updated dependencies: conda-forge tipically has relatively recent version of the dependencies, so if you want to use a recent vtk or pcl on an old distro …

CI: Add conda-forge based builds on Linux

---

releases/2020.08.patch-01.yaml

See discussion in https://github.com/robotology/robotology-superbuild/issues/485 . Furthermore, I also set yarp-matlab-bindings to v3.4.0 that for an error was still pointing to `master` .

Update versions in 2020.08.patch-01

---

.ci/install_debian.sh
README.md

Three changes: 
* Alphabetize the list of dependencies
* Add `libdc1394-22-dev` dependency, used in the `dragonfly2` YARP device in icub-main enabled by the `ROBOTOLOGY_ENABLE_ICUB_HEAD` option
* Sync dependencies in CI and in the README

Cleanup Debian/Ubuntu apt dependencies 

---

cmake/BuildICUB.cmake

The option was removed in https://github.com/robotology/icub-main/pull/659 .

BuildICUB: Remove options related to GTK2 GUIs

---

README.md

Fix https://github.com/robotology/robotology-superbuild/issues/215 .

Mention long path issues for ROBOTOLOGY_ENABLE_ROBOT_TESTING  component

---

.github/workflows/ci.yml

Remove workaround for https://github.com/robotology/robotology-superbuild/issues/479 . To be merged after https://github.com/robotology/robotology-superbuild/pull/493 .

Remove workaround for brew install with taps

---

.github/workflows/ci.yml

This is a workaround for https://github.com/robotology/robotology-superbuild/issues/495, but as [mamba](https://github.com/mamba-org/mamba) is faster and with less dependencies, it is also a step forward to what we would like to offer to the users in the future.

conda-forge CI: Use mamba instead of conda

---

.github/workflows/ci.yml

~The v0.5.0 is still a prerelease, if the compilation with these dependencies fails fixes will be deployed. Once the compilation with the new archive is working, the v0.5.0 release of robotology-superbuild-dependencies-vcpkg will be made official.~
The release is working fine, so it is now an official release: https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/releases/tag/v0.5.0 .
> ~Furthermore, switch from using wget (that needs to be manually installed via `choco`) to using curl (that is already installed on Windows, see https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows).~
Obviously, trying to change two things at the same time always bite you back. I am reverting the wget/curl change for now.

GitHub Actions: Bump used vcpkg-robotology archive to v0.5.0

---

.github/workflows/ci.yml

Workaround for https://github.com/robotology/robotology-superbuild/issues/494 . I guess eventually only a single version of Python will be installed, and fixing the situation now just on Debian sid is not a priority.

Disable Python on Docker builds to avoid Debian sid problems

---

.github/workflows/ci.yml
releases/2020.11.yaml

First step for https://github.com/robotology/robotology-superbuild/issues/500 .
This PR adds a `2020.11.yaml` file, bump it the YCM version to an unreleased commit from the 0.12 branch. Furthermore, the 2020.11 release is added to the CI, while the older relase are removed.
The rationale is that old releases will be broken by the enabling of portaudio dependencies, see  https://github.com/robotology/robotology-superbuild/pull/499#issuecomment-712121774  . 
For use old releases, it is still possible to checkout the relative tag, as discussed in the release notes (see for example https://github.com/robotology/robotology-superbuild/releases/tag/v2020.08).

Add initial files for the 2020.11 release

---

.ci/install_debian.sh
.github/workflows/ci.yml
README.md
cmake/BuildYARP.cmake
cmake/ProjectsTagsStable.cmake
releases/2020.11.yaml

This PR add the dependency on portaudio on Linux, macOS and Windows, and enable by default the compilation of the YARP devices related to audio. Fix https://github.com/robotology/robotology-superbuild/issues/284 .

Add portaudio dependency and enable audio-related devices in YARP

---

.github/workflows/ci.yml

A lot of repo are failing on `brew upgrade` with error: 
~~~
==> Pouring python@3.9-3.9.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
Warning: These files were overwritten during `brew link` step:
The formula built, but is not symlinked into /usr/local
Could not symlink lib/pkgconfig/python3-embed.pc
Target /usr/local/lib/pkgconfig/python3-embed.pc
is a symlink belonging to python@3.8. You can unlink it:
brew unlink python@3.8
~~~
Let's try to fix those. As first step, let's try to remove the workaround added for https://github.com/actions/virtual-environments/issues/1811 .

GitHub Actions: Fix Homebrew problem

---

.github/workflows/ci.yml

Avoid the add-path/set-env regression that will be removed tomorrow .

CI: Bump setup-miniconda Action to v2

---

CMakeLists.txt
README.md
cmake/Buildwalking-teleoperation.cmake
cmake/Buildyarp-device-ovrheadset.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/511 .

If ROBOTOLOGY_USES_OCULUS_SDK is enabled compile yarp-device-ovrheadset

---

.github/workflows/ci.yml

See https://github.com/actions/virtual-environments/issues/1814 for more details on the environment.

CI: Test on macOS 11.0 Big Sur

---

releases/2020.11.yaml

The new release of `whole-body-estimators` was reported by @prashanthr05  in https://github.com/robotology/robotology-superbuild/issues/500#issuecomment-724180794 . 
For the `whole-body-controllers`, with @CarlottaSartore we noticed that the 2020.08-patch01 contained a rather old version of `whole-body-controllers`, so we bumped it. fyi @gabrielenava

Update whole-body-controllers and whole-body-estimators tags for release 2020.11

---

.github/workflows/ci.yml

* Be explicit and avoid the use of `<os>-latest` images 
* Add Ubuntu-20.04 job without Docker
* Change checks on operating system to use contains instead of exact match of the string

CI: Cleanup CI scripts

---

.github/workflows/ci.yml

Modern version of https://github.com/robotology/robotology-superbuild/pull/504 . Now the gazebo build has been refreshed, so everything should work fine. 
For more details on what conda and conda-forge are, and why it useful to have a CI with them, please see https://github.com/robotology/robotology-superbuild/pull/484#issue-501112882 . For the specific case of macOS, having an build that is not using Homebrew should permit us to distinguish the quite frequent Homebrew failures from the actual macOS compilation problems (that should create a failure in both conda and Homebrew macOS jobs).

GitHub Actions: Enable conda-forge CI on macOS

---

releases/2020.11.yaml

After release of wearables `v1.1.0`, I am updating the tag for Release 2020.11.
cc @Yeshasvitvs

Update wearables tag for release 2020.11

---

releases/2020.11.yaml

See https://github.com/robotology/idyntree/releases/tag/v2.0.0 .

Bump iDynTree version to v2.0.0 in 2020.11 distro

---

README.md
doc/developers-faqs.md
doc/profiles.md

Over the years the README of the superbuild has grown complex. To make it more readable, let's move the CMake options-related documentation in another page, and just keep installation instructions in the main README. This change is in view of fixing https://github.com/robotology/robotology-superbuild/issues/505 .

Restructure README moving CMake options documentation in separate file

---

README.md

See https://github.com/robotology/robotology-superbuild/pull/534 for more details.

Add note on Xcode 12 compatibility

---

releases/2020.11.yaml

For YCM and YARP in absence of minor releases with the portaudio fixes (see https://github.com/robotology/robotology-superbuild/pull/499) we get the latest commit from their stable branches. 
For icub-gazebo and iDynTree we bump to the latest tags.

Update some releases for the 2020.11

---

releases/2020.11.yaml

Propagating the change https://github.com/robotology/robotology-superbuild/commit/8b8815db5c3d741e309a23dd978350ce04161998 from `releases/2020.11` branch to master.

2020.11 : Bump icub-models version to 1.18.1

---

README.md
doc/profiles.md

Following this issue, https://github.com/robotology/robotology-superbuild/issues/539, with this PR we move the `matio` library dependency from Dynamics profile to the main superbuild dependency.

Move matio library dependency from Dynamic profile to the main superbuild dependency

---

CMakeLists.txt
cmake/Buildbipedal-locomotion-framework.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/2020.11.yaml

In particular, check if https://github.com/coin-or/CppAD/issues/60 is fixed.

Enable cppad on Windows

---

.github/workflows/ci.yml

Switch to install mamba and conda-forge channels as documented in https://github.com/conda-incubator/setup-miniconda/tree/v2.0.1#example-6-mamba , instead of using an ad-hoc procedure, that probably is creating problem, see https://github.com/robotology/robotology-superbuild/issues/552 .

GitHub Actions: Install mamba as documented in setup-miniconda

---

.github/workflows/ci.yml

Fix https://github.com/robotology/robotology-superbuild/issues/565 .

Add workarounds to fix Homebrew CI

---

.github/workflows/ci.yml

Similar to https://github.com/robotology/robotology-superbuild/pull/484 but for Windows. The lack of direct Visual Studio 2019 support (see https://github.com/conda-forge/vc-feedstock/issues/20) has been addressed by explicitly using the Visual Studio 16 2019 generator.

GitHub Actions: Enable conda-forge CI on Window

---

doc/profiles.md

Related to https://github.com/robotology/robotology-superbuild/issues/28 .
@HuitongIIT can you please check if this is clear enough? Thanks!

Add documentation on system dependencies for ROBOTOLOGY_USES_PYTHON option

---

.github/workflows/ci.yml
README.md

Fix https://github.com/robotology/robotology-superbuild/issues/568, even if actually we never migrate from `qt5` to `qt`, so we will not have problems if `qt` will install `qt6` .

Update brew documentation and CI scripts to refer to qt@5

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

20210000.1 was recently released, and the bipedal-locomotion-framework CI has been already tested with a master version of CppAD close to this release (see https://github.com/dic-iit/bipedal-locomotion-framework/actions). In this way, we can stop depending on a unreleased checkout for CppAD.

Bump CppAD version in ProjectsTags***.cmake to a relased version

---

README.md

@Iaxama @2103simon feel free to approve if you think that this change may be useful

Specify directory that should be installed if robotology-superbuild is installed on the iCub laptop

---

cmake/BuildLieGroupControllers.cmake
cmake/Buildbipedal-locomotion-framework.cmake

This has been required by https://github.com/dic-iit/bipedal-locomotion-framework/pull/167 . Better to do it before that is merged so we don't break CI.

Add LieGroupControllers recipe

---

cmake/ProjectsTagsStable.cmake

blf master now depends on iDynTree devel, so until the next iDynTree release let's use an old commit of bipedal-locomotion-framework .

Fix bipedal-locomotion-framework version for Stable branches

---

cmake/RobotologySuperbuildOptions.cmake

The bindings where installed in `python2.7` for Python <= 2, but for Python >= 3 they are actually installed in `python3`. 
Fix https://github.com/robotology/robotology-superbuild/issues/428 . Thanks @torsten93 for reporting the issue.

Fix assumed installation path of Python bindings

---

.github/workflows/ci.yml
releases/2021.02.yaml

Following the procedure described in https://github.com/robotology/robotology-superbuild/blob/master/doc/developers-faqs.md#how-to-do-a-new-release . For now I just copied the 2020.11 file, by just setting bipedal-locomotion-framework to the specific commit that is compatible with iDynTree < 3 .

Create 2021.02.yaml release file

---

CMakeLists.txt

Leftover from https://github.com/robotology/robotology-superbuild/pull/556 . All the repos were now cloned in src, except for YCM.

Use src folder also for YCM

---

.github/workflows/ci.yml

The GitHub Actions macOS has been failing with:
~~~
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
Error: Process completed with exit code 1.
~~~
I do not know the root cause of this, but I hope that this command was not actually necessary as we do not have it in the README, so I think we can try to remove it.

Change commands used to instll xquartz with homebrew cask

---

cmake/BuildICUB.cmake

In particular, this should be enabled if the `ROBOTOLOGY_ENABLE_ICUB_HEAD` option of superbuild is enabled and we are on Linux. 
The [`ROBOTOLOGY_ENABLE_ICUB_HEAD`  option](https://github.com/robotology/robotology-superbuild/blob/master/doc/profiles.md#icub-head) is meant to be enabled not only on the iCub head, but also for laptop of developers that need to communicate with internal iCub boards, and in that case if they are on Linux they need to have the `socketcan` YARP device if the want to communicate with CAN boards via the [ESD CAN-USB/2 device](https://esd.eu/en/products/can-usb2). 
This was actually already intended, as the documentation says (in https://github.com/robotology/robotology-superbuild/blame/v2020.11/doc/profiles.md#L137):
> On Linux all the software necessary to …

In ICUB compilation set ENABLE_icubmod_socketcan to ON when appropriate

---

.github/workflows/ci.yml

As https://github.com/conda-forge/gsl-feedstock/pull/55 was merged, we don't need to manually patch the header file to fix https://github.com/conda-forge/gsl-feedstock/issues/50 .

Remove gsl on Windows conda workaround in CI

---

.gitignore

Leftover from https://github.com/robotology/robotology-superbuild/pull/556 . The `src` was not ignored, while `robotology` and `external` were still ignored.

Ignore src directory, not old robotology and external

---

.github/workflows/ci.yml

Our Debian Sid job is using the `debian:sid` docker image from https://hub.docker.com/_/debian, but that one is update approximately once a month. To test the actual latest package, we run apt-get upgrade. This should also permit to get faster any update. Also with this change the debian:sid build continues to fail, so for the time being we also disable the Gazebo compilation there.

Run apt-get upgrade in Debian Sid and disable Gazebo on debian:sid for now

---

.github/workflows/ci.yml

First step in the direction of https://github.com/robotology/robotology-superbuild/issues/597 . 
Having a nice subset of the combinations of macOS builds would be better, but apparently the logic with which GitHub Actions deals with the combinations has changed so doing that would require looking into that. As we never had problems just on 11.0 that were not on 10.15, I think we can first doing that.

Remove macOS 11.0 jobs

---

.github/workflows/ci.yml

Bump the version used in the CI.

Bump version of robotology-superbuild-dependencies-vcpkg to 0.6.0

---

cmake/Buildblocktestcore.cmake

The YCM dependency was added in https://github.com/robotology/blocktest/commit/dce9197e5b58adf37697013a9736fc3cb0a246e6 but was never propagated here. 
We never realized this because by chance YCM always got compiled first and blocktestcore was lucky enough to find it. However, I noticed that the dependency was missing by experimenting with conda package generation in https://github.com/traversaro/robotology-superbuild/runs/1797950461 . While generating conda packages, each package is compiled in a sandbox where only the explicitly specified dependencies are available, and so there I noticed that blockfactory was not compiling without YCM.

Add dependency of blocktestcore on YCM

---

.github/workflows/ci.yml

https://github.com/conda-forge/freeglut-feedstock/issues/26 was fixed, so we can finally remove the use of the hardcoded freeglut version.

CI Conda: Remove pinning of freeglut in Windows

---

cmake/ProjectsTagsStable.cmake

Since iDynTree 3 has been released this workaround can be removed

Remove blf tag in ProjectsTagsStable

---

doc/conda-forge.md

The documentation mirrors the steps used in the CI. At the moment the documentation is not linked in the README to avoid confusing new users, but I preferred to add it so I can point interested user that want to experiment with conda-forge to some exhaustive documentation, as now it is possible to install everything with no workarounds after https://github.com/robotology/robotology-superbuild/pull/603 .
Fix https://github.com/robotology/robotology-superbuild/issues/477 .

Add documentation for installation of robotology-superbuild using conda-forge provided dependencies

---

CHANGELOG.md
cmake/BuildGazeboYARPPlugins.cmake

I was looking into some Dockerfiles used for https://robot-bazaar.iit.it/homepage, and I noticed that there were a few workaround for enabling the GAZEBO_YARP_PLUGINS_HAS_OPENCV  option in gazebo-yarp-plugins compilation. However, I don't remember nor see any reason why that options should be disabled: OpenCV is a dependency of the `Core` profile of the robotology-superbuild, and so enabling  this option just take a bit of space more.

Set GAZEBO_YARP_PLUGINS_HAS_OPENCV to ON in gazebo-yarp-plugins compilation

---

.ci/install_debian.sh
.github/workflows/ci.yml
CHANGELOG.md
README.md
cmake/BuildiDynTree.cmake
doc/vcpkg-dependencies.md
releases/2021.02.yaml
releases/latest.releases.yaml

`IDYNTREE_USES_IRRLICHT` is quite used in the context of the IIT's ANA Avatar XPRIZE, and after the fix in iDynTree 3 to support meshes specified by `package://` in URDF and mouse control, it is a much more useful tool in general, so it make sense to enable it by default.
As iDynTree support for finding the irrlicht installed by vcpkg is only in iDynTree 3, we also bump a few dependencies in latest release.

Enable IDYNTREE_USES_IRRLICHT option for iDynTree and bump released versions

---

CHANGELOG.md
cmake/BuildqpOASES.cmake

As discussed in https://github.com/robotology/robotology-superbuild/issues/239#issuecomment-774983308 . qpOASES will still be compiled but just as a C++ library, such that it can be consumed by WB-Toolbox until https://github.com/robotology/wb-toolbox/issues/180 is fixed.

Disable compilation of qpOASES MATLAB bindings

---

scripts/robotologyUpdateLatestReleases.sh

This simplifies understanding to which package an error is related to. This is related to https://github.com/robotology/robotology-superbuild/issues/605, even if it does not address it in full.

robotologyUpdateLatestReleases: add message when checking for a new version of a package

---

.github/workflows/ci.yml

The C:\ drive has much more space then the D:\ drive that is used by default.
Fix https://github.com/robotology/robotology-superbuild/issues/637 .

GitHub Actions CI: On Windows build on C:\

---

cmake/Buildbipedal-locomotion-framework.cmake

If for any reason or bug YARP or matio-cpp or one of its dependencies are missing, then bipedal-locomotion-framework built by the robotology-superbuild should fail with a clear error, not silently disable the relative support. 
See https://github.com/dic-iit/matio-cpp/pull/41#issuecomment-787496467 for a background on this fix.

Buildbipedal-locomotion-framework.cmake: Set FRAMEWORK_USE_YARP and Buildbipedal-locomotion-framework.cmake option to ON

---

.github/workflows/ci.yml

This ensures that compilation problems are catched early, furthermore that MATLAB binaries will be included in Windows installers.

Enable compilation of ROBOTOLOGY_USES_MATLAB option in CI

---

.github/workflows/update-latest-releases.yml

Closing and opening the PR is sufficient to actually start CI (see https://github.com/robotology/robotology-superbuild/pull/647), so better to clearly state it in the PR message.

Latest releases update: clarify how to start CI

---

doc/profiles.md

While base profile options are support quite well on all platforms, some more advanced options are only supported on a subset of our platforms. For this reason, I added a recap table to quickly show the compatibility between options and platforms:

Add Platform Support Table to options documentation

---

.github/workflows/ci.yml
cmake/Buildcasadi.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

* Use new version of the casadi fork 
* Temporary fix blf version for Stable branch to a version before the use of spdlog, that is incompatible with Ubuntu 18.04 (a few days, just for doing some serious announcements) 
* Disable CI of ROBOTOLOGY_ENABLE_DYNAMICS on Unstable and Ubuntu 18.04

bipedal-locomotion-framework related changes

---

doc/conda-forge.md
doc/install-miniforge.md

While the instructions for building from source (and soon installing from binaries, see https://github.com/robotology/robotology-superbuild/issues/620) the robotology-superbuild packages using conda-forge-provided dependencies should work fine on all possible conda distributions, for all users that are new to conda we suggest to use the [miniforge distribution](https://github.com/conda-forge/miniforge). To avoid confusions, we add some detailed documentation on how to install this conda distribution.

 Add detailed recommended instructions on how to install miniforge3 conda distribution

---

cmake/Buildcasadi.cmake

As they are probably not necessary when compiling via the superbuild.

Buildcasadi: Disable compilation of examples

---

releases/latest.releases.yaml

We're required now to maintain `icub-firmware-models` as well.
This PR just introduces it in our pipeline.
To be discussed how to deal with it.
As of now, the new repo sports only `master` and `devel` branches, no tags.

Add icub-firmware-models

---

releases/2021.02.feat-01.yaml

The release is available in https://github.com/robotology/robotology-superbuild/releases/tag/v2021.02.feat-01 . The tags are based on the `2021.02` one, with this diff: https://github.com/robotology/robotology-superbuild/commit/13f56b91ea65c8b4a8a9d5cb92af88b37fd62a19 .

Add 2021.02.feat-01.yaml

---

.github/workflows/ci.yml

This is also to have a platform in which we test the use of Kitware APT Repository. The test is working successfully, so apparently there are no specific problems with CMake 3.20 @drdanz .

Add Docker-based job for apt-based installation with Ubuntu 18.04

---

.github/workflows/generate-conda-packages.yaml

There was a bug in the condition for which conda packages are uploaded, in particular for scheduled jobs the generated packages were not uploaded (see https://github.com/robotology/robotology-superbuild/actions/runs/699934415 for an example).

Fix upload of Conda packages triggered by schedule

---

cmake/Buildblocktest-yarp-plugins.cmake
cmake/Buildblocktestcore.cmake

`blocktest` and `blocktest-yarp-plugins` contained the wrong conda version (due to the some old workarounds). This PR should fix this.

Fix wrong conda versions for blocktest related packages

---

doc/conda-forge.md

When building from sources or from binaries, we were implicitly assuming that the user already had the `conda-forge` channel configured by default. While this is the case for the `miniforge` distribution that we **suggest** to use, it may not be true for users or system using other distributions such as miniconda (see for example https://github.com/dic-iit/bipedal-locomotion-framework/issues/230#issuecomment-815562835) or anaconda (https://github.com/robotology/robotology-superbuild/issues/679).
For this reason, it make sense to modify the instructions to always specify the `-c conda-forge` option. This is also useful for the future, when we may migrate packages from the `robotology` channel to the `conda-forge` one, and we want the `conda-forge` one to have the precedence.

In conda docs explicitly indicate when the use of conda-forge channel  is needed

---

.github/workflows/ci.yml

In this list, two commands are executed:
* `mamba list`, to print the exact packages installed in the conda environment
* `env` to print the environment variables set
This are useful to quickly check what changed in case of CI failures (such as https://github.com/robotology/robotology-superbuild/issues/681), as it is simplify the process of checking the difference to just copy&paste the output of that step in meld or any other diff software.

Add "Print Used Environment" step to conda CI

---

CMakeLists.txt

On conda, the Gazebo's environment variables are already set in the environment activation scripts, so there is no need to source it manually in the `setup.sh` script. Actually, we need to make sure that the apt-installed Gazebo setup.sh is not accidentally sourced, as that could conflict with the conda-installed one.

Do not source hardcoded Gazebo's setup.sh on Conda

---

cmake/Buildcasadi.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

Before merging the PR we should use casadi version `3.5.5.3`. I've just created the tag. I don't know if I can bump the new tag in this PR or handle it in a separate PR

Add the possibility to compile the casadi python bindings

---

cmake/BuildYARP.cmake

See https://github.com/robotology/yarp/pull/2552 . As we now need to support both YARP 3.4 (Stable branches and latest releases) and YARP 3.5 (Unstable branches) we will pass both options, as this should work fine and avoid to trigger the bug https://github.com/robotology/yarp/issues/2556 .
Fix https://github.com/robotology/robotology-superbuild/issues/695

Specify both YARP 3.4 and 3.5 style options for depthimage portmonitor

---

cmake/Buildcasadi.cmake

Follow up of https://github.com/robotology/robotology-superbuild/pull/694, fix https://github.com/robotology/robotology-superbuild/issues/698 by explicitly requesting to use Python3, that means that the system Python should not be used on macOS .
The use of this option is copied from https://github.com/conda-forge/casadi-feedstock/blob/391139c859e1fba1321818bae27b6ca11fa4081e/recipe/build.sh#L7 .

Buildcasadi: pass WITH_PYTHON3 option when Python bindings are built

---

.github/workflows/generate-conda-packages.yaml
scripts/robotologyBumpCondaBuildNumber.sh

To ensure that each new build of the packages get correctly uploaded, even if the package version was not uploaded (for example because one of the dependencies that influences its ABI was updated) we have a `CONDA_BUILD_NUMBER` parameter in the `conda/cmake/CondaGenerationOptions.cmake` , that specifies the [Conda build number](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-number-and-string) that is used by all Conda packages.
This parameter should be bumped at each successful generation and upload of Conda binaries, and until now I have done this manually (see for example https://github.com/robotology/robotology-superbuild/commit/7a10e5088ad33a2166bb5635038b9c58fbb5fc8c and https://github.com/robotology/robotology-superbuild/commit/0df5e6a997ce7 …

Add bump-conda-build-number job to generate-conda-packages

---

.github/workflows/generate-conda-packages.yaml
conda/conda_build_config.yml
doc/conda-recipe-generation.md

As documented in https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#creating-conda-build-variant-config-files, the `conda_build_config.yaml` files can be used to specified the specific version of the libraries used, to build multiple versions of the libraries, or to specific more options. 
Until now when generating conda packages we just used our local `conda/conda_build_config.yml` file, now as explained in https://github.com/robotology/robotology-superbuild/issues/708 we will switch to consider the conda-forge `conda_build_config.yaml` (mantained at https://github.com/conda-forge/conda-forge-pinning-feedstock) to ensure the maximum compatibility of our binaries with the one compiled by conda-forge.

generate-conda-packages: Use conda-forge-pinning conda_build_config.yaml

---

doc/cmake-options.md

As they were removed in https://github.com/robotology/robotology-superbuild/pull/613 .

Remove references to qpOASES MATLAB bindings

---

doc/matlab-one-line-install.md
scripts/install_robotology_packages.m

Fix https://github.com/robotology/robotology-superbuild/issues/713 .
In particular, if you are interesting in a pure MATLAB workflow (so without launching **anything else** via terminal, so no Gazebo) to install all the MATLAB and Simulink robotology packages it should be sufficient to run:
~~~matlab
websave('install_robotology_packages.m', 'https://raw.githubusercontent.com/traversaro/robotology-superbuild/fix/713/scripts/install_robotology_packages.m')
install_robotology_packages
robotology_setup
~~~
This will install everything in a `robotology-gazebo` local directory, without perturbing anything else in your system. Once installed, you just need to re-run the `robotology_setup` script (or add it in your setup) to make the library available again. The overall installation process …

Create MATLAB script for simple local few line installation of MATLAB packages

---

cmake/Buildwalking-teleoperation.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/726 . The `<pkgname>_CONDA_VERSION` variables are useful when for any reason we want to override the version specified in the tag, but by default it should not be set, as the tag version (removing the `v`  prefix) is typically used instead (see https://github.com/robotology/robotology-superbuild/blob/master/conda/recipe_template/meta.yaml#L5).

Remove leftover walking-teleoperation_CONDA_VERSION

---

doc/developers-faqs.md

As I was writing the description of https://github.com/robotology/robotology-superbuild/pull/728, I noticed that  `<pkg>_CONDA_VERSION` was not documented.

Document <pkg>_CONDA_VERSION CMake variable

---

cmake/Buildwearables.cmake

The PR in `wearables` https://github.com/robotology/wearables/pull/113 adds `YARP_telemetry` as one of its dependency. 
This PR complements that change.

Add YARP_telemetry dependency for wearables

---

.github/workflows/ci.yml

Several changes have been done to the superbuild since that release (introduction of YARP_telemetry among the others), so that release does not contain tags for some subprojects. To avoid confusion, it is better to now remove it from the CI. In any case, the fact that those release has been compiling fine on Ubuntu 20.04 has been already tested.

Remove release v2021.02 from CI

---

doc/cmake-options.md

For YARP Vectors, the `fromMatlab` methods expects the YARP vector to be of the same size of the passed MATLAB vector, see https://github.com/robotology/robotology-superbuild/issues/515 and https://github.com/robotology/yarp-matlab-bindings/issues/62 .

Fix MATLAB and Octave snippets

---

cmake/Buildhuman-dynamics-estimation.cmake

Some time ago, we added `HUMANSTATEPROVIDER_ENABLE_VISUALIZER` cmake option for enabling the human-dynamics-estimation visualizer (https://github.com/robotology/human-dynamics-estimation/pull/230).
Since it is quite stable now, I think it makes sense to enable it as default `on`

Add enable Visualizer to HumanDynamicsEstimation

---

cmake/ProjectsTagsStable.cmake

This was removed in https://github.com/robotology/robotology-superbuild/pull/739, but now the CI is failing with:
~~~
2021-05-19T03:10:22.9978261Z /usr/bin/c++ -DSPDLOG_COMPILED_LIB -DTSID_EXPORTS -D_USE_MATH_DEFINES -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/bipedal-locomotion-framework/src/TSID/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/bipedal-locomotion-framework/src/Contacts/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/bipedal-locomotion-framework/src/Math/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/bipedal-locomotion-framework/src/ParametersHandler/include -I/home/runner/work/robotology-superbuild/robotology-superbuild/src/bipedal-locomotion-framework/src/GenericCo …

Use again fixed checkout for bipedal-locomotion-framework Stable

---

.github/workflows/release.yml
packaging/windows/CMakeLists.txt

This PR add a github action for creating a new `robotology-superbuild` release, it automatize these steps: https://github.com/robotology/robotology-superbuild/blob/master/doc/developers-faqs.md#how-to-do-a-new-release
For doing this I changed the CMakeLists of windows packaging https://github.com/robotology/robotology-superbuild/commit/a2e8999f97d87940dd0c527266e528d711a1b215 for make easier the sed command, the idea is that on master the `INSTALLER_VERSION` is empty(or we can put something like  `master` and then it is versioned in the `releases/yyyy.mm` branch.
This Action can be triggered only by hand specifying the version of the release you want to create:
Here are the steps:
- Copy `latest.yml` into `yyyy.mm.yml` commit and push it on master …

Add Release Github Action

---

cmake/BuildWBToolbox.cmake

This adds the explicit dependency on `OsqpEigen` due to https://github.com/robotology/wb-toolbox/pull/209 (even if it should actually work already as wb-toolbox already dependency transitevly on OsqpEigen via iDynTree.

WBToolbox: Explicitly enable dependency on ICUB, qpOASES and OsqpEigen

---

cmake/Buildbipedal-locomotion-framework.cmake

This fixes https://github.com/robotology/robotology-superbuild/issues/757 . The issue would be fixed also as soon as the new version of blf is released, but in any case the logic of installing in the active sitepackage when building a conda package is for sure more robust also against future regressions.

blf: Always set FRAMEWORK_DETECT_ACTIVE_PYTHON_SITEPACKAGES to on when generating conda packages

---

.github/workflows/ci.yml
doc/cmake-options.md
releases/latest.releases.yaml

Workaround for https://github.com/robotology/robotology-superbuild/issues/753 taken from https://github.com/osrf/homebrew-simulation/issues/1486#issuecomment-850218440

Add in CI and document workaround for macOS/Homebrew Gazebo/tbb failures

---

conda/multisheller/yarp_activate.msh
conda/multisheller/yarp_deactivate.msh

Without that, you get this error:
~~~
generate_conda_recipes_from_metadatadata: generating recipe for package ycm-cmake-modules
/home/runner/work/robotology-superbuild/robotology-superbuild/build/conda/generated_recipes/ycm-cmake-modules
Traceback (most recent call last):
File "/home/runner/work/robotology-superbuild/robotology-superbuild/conda/python/generate_conda_recipes_from_metametadata.py", line 139, in <module>
main()
File "/home/runner/work/robotology-superbuild/robotology-superbuild/conda/python/generate_conda_recipes_from_metametadata.py", line 124, in main
generate_scripts_from_multisheller_file(multisheller_scripts_dir + "/" + activation_script_msh, recipe_dir, "activate")
File "/home/runner/work/robotology-superbuild/robotology-superbuild/conda/python/generate_conda_recipes_fr …

Fix multisheller scripts for YARP

---

.github/workflows/ci.yml
CHANGELOG.md
doc/cmake-options.md

MATLAB is already tested on Conda/Windows and distributed as Conda binaries (including in convenient form such as the one-line installer: https://github.com/traversaro/robotology-superbuild.git). There was a recent regression in the vcpkg-based installer due to MATLAB, the easier choice is just to disable MATLAB in the vcpkg-installer, and just support it on Conda/Windows .

Disable ROBOTOLOGY_USES_MATLAB in vcpkg/Windows CI

---

scripts/install_robotology_packages.m

The directory name can be very long, and this would mean that the message directed to the user is hidden on the right part of the screen. Add a new line to ensure that the error is printed in a visible part of the screen.
@DanielePucci if you want to test this new version, you can do by running:
~~~matlab
websave('install_robotology_packages.m', 'https://raw.githubusercontent.com/robotology/robotology-superbuild/fix/777/scripts/install_robotology_packages.m')
install_robotology_packages
robotology_setup
~~~
(I just took https://github.com/robotology/robotology-superbuild/blob/master/doc/matlab-one-line-install.md and substituted `master` with `fix/777`)
Fix https://github.com/robotology/robotology-superbuild/issues/777 .

install_robotology_packages MATLAB helper: do not print messages after directory name

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
cmake/Buildbipedal-locomotion-framework.cmake
doc/conda-forge.md
doc/vcpkg-dependencies.md

Fix https://github.com/robotology/robotology-superbuild/issues/763 . I added it as a dependency in all points, I am just missing https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/45 to also bump the version of vcpkg dependencies used in CI.

Ad nlohmann-json as dependency of the superbuild

---

.github/workflows/ci.yml

This will permit to trigger new jobs without creating fake PRs such as https://github.com/robotology/robotology-superbuild/pull/784 .

Add workflow_dispatch to C++ CI

---

scripts/install_robotology_packages.m

On Windows, add quotes to correctly invoke conda in path with spaces. 
On Linux/macOS, print a clear error until https://github.com/conda/constructor/pull/449 is fixed.
Fix https://github.com/robotology/robotology-superbuild/issues/780 .

install_robotology_packages: Handle correctly install_path with spaces

---

.github/workflows/ci.yml

This is much less invasive workaround for https://github.com/robotology/robotology-superbuild/issues/785 .

Pin libsolv to 0.7.18 in conda CI

---

doc/install-miniforge.md

The default installation path has been modified.
Fix https://github.com/robotology/robotology-superbuild/issues/790 .

Fix documentation of how to install Miniforge3 on Windows

---

CHANGELOG.md
cmake/BuildYARP.cmake

All the fake*** devices are quite useful for tutorials and tests and they do not have strange deps, so let's enable them. 
Let's check CI with attention as it is possible that some of this devices have compilation problems in some platforms tested by CI.

BuildYARP: Enable all fake** devices

---

scripts/install_robotology_packages.m

As per discussion in https://github.com/robotology/robotology-superbuild/pull/783 we are not going to make `casadi-matlab-bindings` as dependency of whole-body-controllers, I think it make sense that in install_robotology_packages script (used in the one-line matlab installation, see https://github.com/robotology/robotology-superbuild/blob/master/doc/matlab-one-line-install.md) also installs `casadi-matlab-bindings`.

install_robotology_packages: Install also casadi-matlab-bindings

---

.github/workflows/generate-conda-packages.yaml
cmake/BuildOsqpEigen.cmake
cmake/BuildRobotTestingFramework.cmake
cmake/Buildevent-driven.cmake
conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake
conda/recipe_template/meta.yaml

As osqp-eigen and YCM are now available in conda-forge (see https://github.com/conda-forge/staged-recipes/pull/15309 and https://github.com/conda-forge/osqp-eigen-feedstock) we can now avoid building our own `osqp-eigen`, `ycm-cmake-modules` and `robot-testing-framework` packages in the robotology channel, and just rely on the one provided by `conda-forge`. 
This is done by defining in `Build<project>.cmake` the `<project>_CONDA_PKG_NAME` and `<project>_CONDA_PKG_CONDA_FORGE_OVERRIDE` variables, as described in https://github.com/robotology/robotology-superbuild/blob/master/doc/developers-faqs.md#how-to-ensure-that-binary-packages-are-correctly-generated-for-a-new-package . We also removed the `<project>_CONDA_DEPENDENCIES` as that was used just in the conda binary generation phase.
Part …

OsqpEigen, YCM and robot-testing-framework: Switch to use conda-forge binary package when generating conda packages

---

.github/workflows/ci.yml

While debugging https://github.com/robotology/robotology-superbuild/issues/815, I noticed that this dependency was missing so icub-main in CI was actually not compiling iCub_SIM at all, as OpenGL was not correctly found.

Add missing mesa-libgl-devel-cos6-x86_64 dependency for Conda on Linux

---

CHANGELOG.md
cmake/Buildhuman-dynamics-estimation.cmake
cmake/BuildiDynTree.cmake
cmake/Buildidyntree-yarp-tools.cmake
cmake/RobotologySuperbuildLogic.cmake
releases/latest.releases.yaml

Furthermore, remove any dependy on YARP or ICUB on iDynTree.
Currently missing points:
* A release of iDynTree including https://github.com/robotology/idyntree/pull/887
* A release of idyntree-yarp-tools

Add idyntree-yarp-tools

---

.github/workflows/generate-conda-packages.yaml

As it was clear in https://github.com/robotology/robotology-superbuild/issues/822, unfortunatly we were not dumping the exact environment used to run the `generate-conda-packages` job, and this lead us to a regression that it is difficult to debug. Better to add a `mamba list` step for the CI for the future.
Furthermore, pin mamba to 0.14.1 and boa to 0.5.0 as a workaround for https://github.com/robotology/robotology-superbuild/issues/822 and https://github.com/mamba-org/boa/issues/165 .
Fix https://github.com/robotology/robotology-superbuild/issues/822 .

Add mamba list to generate-conda-packages job and pin mamba and boa to 0.5.0 and 0.14.1

---

.github/workflows/ci.yml

Workaround for:
* https://github.com/robotology/robotology-superbuild/issues/826
* https://github.com/actions/virtual-environments/issues/3733

Add workaround for Homebrew failure related to mongodb-community

---

cmake/ProjectsTagsStable.cmake

Much smaller prerequisite of https://github.com/robotology/robotology-superbuild/issues/828, I think that it should not be a problem to merge if CI passes, as the possibility of runtime problems created by YCM is relatively low.

Bump YCM to 0.13 in ProjectsTagsStable.cmake

---

.github/workflows/ci.yml

All the problem should be solved by recent mamba versions, see: 
* https://github.com/robotology/robotology-superbuild/issues/785
* https://github.com/mamba-org/mamba/issues/986

conda CI: Remove pinning to old libsolv version

---

.github/workflows/generate-conda-packages.yaml

All the issue should be solved now, see:
* https://github.com/robotology/robotology-superbuild/issues/822
* https://github.com/mamba-org/boa/issues/165 .

generate-conda-packages: Remove mamba and boa pinning

---

.github/workflows/ci.yml

Now `mongodb-community` is not installed, so tryng to uninstall it result in failure.

Remove workaround for  https://github.com/actions/virtual-environments/issues/3733

---

.github/workflows/ci.yml

The CI has been using the defaults channel (even if this was not wanted) for a long time, see https://github.com/conda-incubator/setup-miniconda/issues/186 and https://github.com/robotology/robotology-superbuild/issues/669 . However, since yesterday this created a compilation error:
~~~
2021-07-30T02:25:20.1711320Z /usr/share/miniconda/envs/test/x86_64-conda-linux-gnu/include/c++/9.3.0/ctime:80:11: error: '::timespec_get' has not been declared
2021-07-30T02:25:20.1712202Z    80 |   using ::timespec_get;
2021-07-30T02:25:20.1712597Z       |           ^~~~~~~~~~~~
~~~
For this reason, better to cleanup the use of conda channels in the CI, making sure that we don't use `defaults` at all, by using Mambaforge as base installer.
Similar to https://github.com/robotology/yarp-telemetry/pull/141 . …

Fix Conda CI on Linux avoiding to use the defaults channel by installing Mambaforge

---

doc/conda-forge.md
doc/install-mambaforge.md

This is a result of a feedback that came from our first training on conda: the time taked by conda install was incompatible with quickly explaing how conda environment works, so better to officially switch to mamba to ensure that the users have a smooth and fast user experience.

Migrate conda documentation to use mamba instead of conda

---

doc/conda-forge.md

On Windows command prompt is preferred as some projects have problem in activating their environment in Powershell, while in general it is a good idea to reduce the possibility of conflicts in environment variables.

In Conda documentaton, document that the preferred shell on Windows is Command Prompt and that the environment should be as clean as possible

---

.github/workflows/ci.yml
README.md
apt.txt
scripts/install_apt_dependencies.sh

This fixes https://github.com/robotology/robotology-superbuild/issues/854 . I took the occasion to also move in `install_apt_dependencies.sh` the installation of nlohmman-json library.

Handle different names of libdc1394 package in different distributions

---

cmake/Buildbipedal-locomotion-framework.cmake
cmake/Buildmanif.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/802 .

Enable compilation of Python bindings of manif and bipedal-locomotion-framework also on Windows

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

The need for it emerged in https://github.com/robotology/robotology-superbuild/pull/844#issuecomment-893293323 but was fixed by https://github.com/robotology/walking-teleoperation/pull/67 .

Remove use of devel branch for walking-teleoperation stable branch

---

.github/workflows/icubTechIIT_code.yml

In this PR I have added a step to retrieve the app id and the private key from the GitHub App, in order to generate a token that will be used for the repository dispatch, instead of using the old PAT.

Updated repository dispatch with GitHub App usage

---

cmake/IncludeUrl.cmake
cmake/YCMBootstrap.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/843 . This was a regression caused by https://github.com/robotology/robotology-superbuild/pull/829 .

Update IncludeURL and YCMBootstrap to solve warning

---

CHANGELOG.md

Even if 2021.08 was already tagged, this is not a big problem, as the changelog will be manually copied in the release notes.

Update CHANGELOG for 2021.08 release

---

cmake/BuildYARP_telemetry.cmake
cmake/Buildblocktestcore.cmake
cmake/Buildevent-driven.cmake
cmake/Buildicub_firmware_shared.cmake
cmake/Buildyarp-device-ovrheadset.cmake

Using `find_or_build_package(YCM)` result in a warning being generated: 
~~~
CMake Warning (dev) at
build/install/share/YCM/modules/FindOrBuildPackage.cmake:212 (message):
A YCM target already exists before including BuildYCM.
Call Stack (most recent call first):
cmake/BuildYARP_telemetry.cmake:7 (find_or_build_package)
build/install/share/YCM/modules/FindOrBuildPackage.cmake:215 (include)
cmake/RobotologySuperbuildLogic.cmake:50 (find_or_build_package)
CMakeLists.txt:63 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
~~~
This happens because there is no `BuildYCM.cmake`  file, and YCM is handled a bit differently from other projects, so the target is always present without the need of using `find_or_build_package(YCM ...)`
Fix …

Remove use of find_or_build_package(YCM ...) to avoid warning

---

.github/workflows/generate-conda-packages.yaml

I tought  https://github.com/robotology/robotology-superbuild/issues/806  was fixed by https://github.com/robotology/robotology-superbuild/pull/838 , but it turns out that indeed another modification was necessary. 
I also tried to use `conda mambabuild`  to check if the issue mentioned in https://github.com/robotology/robotology-superbuild/issues/809#issuecomment-894174951 is still present, if that is the case I will move back to use conda build .

Enable generation of blf conda package

---

.ci/install_debian.sh
.github/workflows/icubTechIIT_code.yml
CHANGELOG.md
cmake/BuildYARP_telemetry.cmake
cmake/Buildblocktestcore.cmake
cmake/Buildevent-driven.cmake
cmake/Buildicub_firmware_shared.cmake
cmake/Buildyarp-device-ovrheadset.cmake
cmake/IncludeUrl.cmake
cmake/ProjectsTagsUnstable.cmake
cmake/YCMBootstrap.cmake
scripts/install_apt_dependencies.sh

In view of `2021.08-feat01` release.
PR backported:
* https://github.com/robotology/robotology-superbuild/pull/862
* https://github.com/robotology/robotology-superbuild/pull/864
* https://github.com/robotology/robotology-superbuild/pull/865
* https://github.com/robotology/robotology-superbuild/pull/866
* https://github.com/robotology/robotology-superbuild/pull/873

Backport useful fixes to releases/2021.08 branch

---

releases/latest.releases.yaml

See https://github.com/robotology/robotology-superbuild/pull/877#issuecomment-913145087 .

Bump icub-models to v1.21.1

---

apt.txt

I remember back in time that the IOL demo needed also the plain `lua` package: see the [YARP doc](https://github.com/robotology/yarp/commit/fa5035fad77d2668ff1cbd82372a3813d4e4e2d4) I updated in this respect.
It's maybe also the right time to upgrade to version `5.2`.

Update apt.txt wrt `lua`

---

CMakeLists.txt

Fix https://github.com/robotology/robotology-superbuild/issues/871 . 
Based on my understanding, the problem is that the binary created by conda is not relocatable, so it contains the wrong paths (in particular, the one of the build machine, not the one of the machine in which it is installed).
In theory, this is a problem that should be solved at https://github.com/conda-forge/qt-feedstock . However, there is already a lot going on on that repo, so it is not even sure if a fix would be merged. Furthermore, updating to Qt 5.15 would solve the problem (thanks to https://www.qt.io/blog/qt-is-relocatable), so it is better to simply wait for 5.15 to arrive in qt-feedstock. In the meanwhile, a simple workaround is to have the superbuild copy the `qt.conf` in the right directory if it detect …

Add workaround for non-relocatable qt used in conda-forge

---

releases/2021.08.1.yaml

Originally added in https://github.com/robotology/robotology-superbuild/pull/887 .

Add 2021.08.1 release to master branch

---

doc/conda-powershell-troubleshooting.md
doc/install-mambaforge.md

This should be more clear w.r.t. to previously available documentation on the fact that as long as we don't fix some issues, it is better to avoid use powershell.
fyi @S-Dafarra @ste93

Clarify in documentation that Powershell does not fully work for conda-based installation

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/856 thanks to https://github.com/coin-or/CppAD/issues/116 and https://github.com/coin-or/CppAD/commit/97bb08348f107bfa9445a362a674889a02bc57ce that is included in `20210000.8` release.
fyi @CarlottaSartore @VenusPasandi

Bump cppad to 20210000.8

---

CHANGELOG.md
cmake/Buildbipedal-locomotion-framework.cmake

While debugging https://github.com/robotology/robotology-superbuild/issues/907, I noticed that the dependency on `UnicyclePlanner` was missing from `bipedal-locomotion-framework`. Even if this does not fix https://github.com/robotology/robotology-superbuild/issues/907, it is an issue worth fixing.

bipedal-locomotion-framework: Add missing dependency on UnicyclePlanner

---

doc/conda-forge.md

I just copied the list from https://github.com/robotology/robotology-superbuild/blob/83a0c595765b96a6de4305406346bcfb33a8f98b/.github/workflows/ci.yml#L81 in the docs. 
This should fix https://github.com/robotology/robotology-superbuild/issues/893 .

Align list of conda-forge robotology-superbuild dependencies between CI and docs

---

CHANGELOG.md
cmake/BuildICUB.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/894 .

In ICUB enable compilation of bcbBattery if ROBOTOLOGY_ENABLE_ICUB_HEAD option is enabled

---

cmake/BuildYARP.cmake

`usbCamera` plugin links `usbCameraRaw`, then if `usbCameraRaw` is not enabled it triggers this error:
```
[ERROR] |yarp.os.YarpPluginSettings| Error while opening /home/ngenesio/robotology/robotology-superbuild/build/install/lib/yarp/yarp_usbCamera.so:
/home/ngenesio/robotology/robotology-superbuild/build/install/lib/yarp/yarp_usbCamera.so: undefined symbol: usbCameraRaw
```

BuildYARP.cmake: fix linking issue for usbCamera

---

.github/workflows/ci.yml
cmake/ProjectsTagsUnstable.cmake
doc/conda-forge.md

For the conda part, `mesalib` should not be actually necessary as we already install `mesa-libgl-cos6-x86_64` and `mesa-libgl-devel-cos6-x86_64`. However, also install `libxshmfence-cos6-x86_64 libxshmfence-devel-cos6-x86_64`.
Fix https://github.com/robotology/robotology-superbuild/issues/925 .
Fix https://github.com/robotology/robotology-superbuild/issues/900 .
Currently blocked by https://github.com/robotology/idyntree-yarp-tools/pull/20 and https://github.com/robotology/whole-body-estimators/pull/131 .

In conda deps do not install mesalib, switch to cos7 and switch back to YARP master in Unstable branches

---

doc/conda-forge.md

`expat-cos6-x86_64` should be `expat-cos7-x86_64`.
See:
* https://github.com/robotology/robotology-superbuild/pull/926 the original pr
* https://github.com/conda-forge/conda-forge.github.io/issues/1436 the indication that probably conda-forge as an whole will be moving to cos7 soon, that actually give even more sense to https://github.com/robotology/robotology-superbuild/pull/926

Fix typo in cdt package to install on conda-forge documentation

---

.github/workflows/ci.yml
doc/conda-forge.md

This is done to mitigate cross-talking problems when compiling YARP in a conda-environment in Arch-based distributions, see https://github.com/robotology/robotology-superbuild/issues/923 .
This is just a mitigation, as the issue is either in the conda-packaged CMake that is able to find system libraries or in the YARP build system, but given that lua is a relative small dependency is not a problematic mitigation.

Install lua as dependency in conda-forge-based installation

---

releases/latest.releases.yaml

GitHub handles the rename quite well, but better to change the names of AMI's repo to use new organization name.

latest.releases.yaml: Change dic-iit repositories to use new name ami-iit

---

.github/workflows/generate-conda-packages.yaml
cmake/BuildGazeboYARPPlugins.cmake
conda/recipe_template/build.sh

* `boa` and `mamba` were quite unstable lately, so pin them to safe version at least for the near future.
* There are strange internal compiler errors when building gazebo-yarp-plugins, so let's build stick to build it against gazebo 11.8 for which this problem do not emerge.
* Add the channel `robotology` when icub-main is built so that the `esdcan` dependency is correctly found (see https://github.com/robotology/robotology-superbuild/pull/935)
Fix https://github.com/robotology/robotology-superbuild/issues/927 .

Fix conda package generation by pinning boa and mamba to known working versions

---

.github/workflows/generate-conda-packages.yaml

Improvements to complete : 
* it seems that `conda mambabuild` does not support correctly the `-c` option to specify the channels
* it seems that unless we set `--set channel_priority strict` for some reason when `icub-main` is built the `yarp` from robotology is found (instead of the one from `local`, i.e. that was previously built). 
* The `--skip-existing` option does not work as expected, so the `icub-main` configuration fails even if `icub-main` is already built. So we remove all the recipe directories manually, and then we build all the rest of recipes without `--skip-existing` option.
With these three fixes, icub-main with esd support is build correctly on Windows, completing the PR https://github.com/robotology/robotology-superbuild/pull/935 .

generate-conda-packages: For icub-main switch to conda build and use strict channel_priority 

---

.ci/install_debian.sh
.github/workflows/ci.yml

Fix/workaround for https://github.com/robotology/robotology-superbuild/issues/944 . For the time being, we do not test Gazebo support for Debian Testing.

Disable Gazebo testing on Debian Testing

---

cmake/Buildbipedal-locomotion-framework.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/951 .

Add OsqpEigen as explicit dependency of bipedal-locomotion-framework

---

.github/workflows/release.yml

After the change described in https://github.com/icub-tech-iit/documentation/pull/172, it is necessary to change the `release` workflow, otherwise the branches will be created with the name `releases/YYYY.MM.0` instead of the correct `releases/YYYY.MM`, as it happened for example with the 2021.11 release: https://github.com/robotology/robotology-superbuild/tree/releases/2021.11.0 .
For the `2021.11` I will manually modify the script, but this modification are there to avoid doing this error again in the future.

Modify release workflow to account for new numbering scheme

---

.github/workflows/ci.yml

Workaround for https://github.com/robotology/robotology-superbuild/issues/955 . Indeed, switching to macos-10.15 works as Xcode 12 is used. However, the problem remains withw Xcode 13.

Switch conda CI to macos-10.15 workers

---

doc/install-mambaforge.md
doc/install-miniforge.md

For some reason, when I first developed this docs, I tought that `%HOME%` was an environment variable defined by default on Windows, but that is not the case as I recently discovered on a brand new Windows system. However, whenever `%HOME%` is needed we can just use `%HOMEDRIVE%%HOMEPATH%` that should work fine as well and is always defined on any Windows system (see https://stackoverflow.com/questions/606483/what-is-the-meaning-of-these-windows-environment-variables-homedrive-homepath).

install-mambaforge docs: Substitute %HOME% references with %HOMEDRIVE%%HOMEPATH%

---

cmake/ProjectsTagsUnstable.cmake

Workaround for https://github.com/robotology/robotology-superbuild/issues/959 .

Use YARP unstable checkout before IRangefinder2D interface changes

---

.github/workflows/generate-conda-packages.yaml

In https://github.com/robotology/robotology-superbuild/issues/955 an issue between conda compilers and macOS SDK in Xcode 13 (that is installed in macos-latest) was found. This PR avoids that issue in  `generate-conda-packages` action by switching to `macos-10.15` image. For consistency, on Linux we use ubuntu-20.04 instead of ubuntu-latest.

Use ubuntu-20.04 and macos-10.15 in generate-conda-packages

---

conda/multisheller/wb-toolbox_activate.msh
conda/multisheller/wb-toolbox_deactivate.msh
conda/multisheller/whole-body-controllers_activate.msh
conda/multisheller/whole-body-controllers_deactivate.msh

Fix https://github.com/robotology/wb-toolbox/issues/228, using the same workaround that was already used in icub-models also in whole-body-controllers and wb-toolbox . 
For a brief explanation of what is going on, [multisheller](https://github.com/mamba-org/multisheller) is the project that we are using to generate "activation scripts" (i.e. the scripts that set the right enviromental variables when you type `conda activate <env>`) for our conda packages for all the terminal we are supporting (bash, zsh, command prompt). For a longer explanation, see last part of  https://github.com/robotology/robotology-superbuild/blob/0bf40cf7d2c05e130b6f7fc1c86b7a87c6fcd373/doc/developers-faqs.md#how-to-ensure-that-binary-packages-are-correctly-generated-for-a-new-package .
The problem is that …

Workaround problem of multiple append in the same if in conda activation scripts in command prompt

---

cmake/BuildGazeboYARPPlugins.cmake

~The use of 11.8 is generating the problem described in https://github.com/robotology/yarp.js/issues/28#issuecomment-997122408, let's try to remove this so the latest gazebo is used.~ 
As gazebo 11.9 still results in internal compiler error, we still require gazebo=11.8 in the build and for now we just add the dependency on dartsim so we get the correct run_exports dependency in gazebo-yarp-plugins.

GazeboYARPPlugins: add dependency on dartsim when generating conda packages

---

doc/conda-forge.md

The documentation and the CI were not coherent. In particular, in the docs the `mesa-libgl-devel-cos7-x86_64` package (that contains the `GL/gl.h` header) was missing.

conda-forge Documentation: Fix documentation on required additional dependencies on Linux

---

conda/multisheller/whole-body-controllers_activate.msh

PR https://github.com/robotology/robotology-superbuild/pull/957 create a regression that broke the `generate-conda-recipes` job. This PR fixes it.

Fix regression in generation of whole-body-controllers recipe introduced by PR 957

---

cmake/BuildGazeboYARPPlugins.cmake
conda/recipe_template/build.sh
conda/recipe_template/meta.yaml

Instead of requiring an old version of Gazebo as done in https://github.com/robotology/robotology-superbuild/pull/937, we switch to use the clang++ compiler if gazebo-yarp-plugins is built. Not a complete fix, but better that use an old version of Gazebo that in the long run forces a old version of all the transitive dependencies of Gazebo.
Fix https://github.com/robotology/robotology-superbuild/issues/966 .

Add workaround for gazebo-yarp-plugins internal compiler error by switching to clang

---

cmake/RobotologySuperbuildOptions.cmake
packaging/windows/CMakeLists.txt
releases/2021.11.1.yaml

First step towards a new release in the 2021.11 series (fyi @Nicogene this is the step I would like to automatize as discussed in https://github.com/robotology/robotology-superbuild/pull/954#issuecomment-993707057).
The file `2021.11.1.yaml` is copied from `2021.11.0.yaml`, we can bump the dependencies that we want to bump in a separate commit/PR.

2021.11 release series: Bump version to 2021.11.1

---

cmake/ProjectsTagsStable.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/978 .

Pin Stable builds to v1.22.0 to workaround lack of YARP 3.6 release

---

cmake/ProjectsTagsUnstable.cmake

Revert https://github.com/robotology/robotology-superbuild/pull/961 as the issue was solved by https://github.com/robotology/gazebo-yarp-plugins/pull/599 .

Use YARP master branch in Unstable tags

---

cmake/YCMLoadVcsYamlInfo.cmake

The procedure for using custom version of repository as described in https://github.com/robotology/robotology-superbuild/issues/280 was not working correctly when the version used were loaded from `.yaml`  file. So, the procedure was working correctly if the `Stable` or `Unstable` as those are loaded via custom .cmake files (see https://github.com/robotology/robotology-superbuild/blob/v2021.11.0/cmake/ProjectsTagsStable.cmake and https://github.com/robotology/robotology-superbuild/blob/v2021.11.0/cmake/ProjectsTagsUnstable.cmake) but not if the version were loaded by `.yaml`, as the `ycm_load_vcs_yaml_info` was overwriting the values specified via the CMake command line.
This PR should fix this.

Fix overriding of <package>_REPOSITORY and <package>_TAG when a distro yaml file is used

---

cmake/ProjectsTagsStable.cmake

As `yarp` and `yarp-matlab-bindings` use a different branch for each minor release, we need to update manually them to ensure that Stable branches use YARP 3.6 .
As now we bump to yarp-3.6, I also removed the workaround added in https://github.com/robotology/robotology-superbuild/pull/979 .

Bump YARP and yarp-matlab-bindings in Stable branches to yarp-3.6

---

releases/2021.11.1.yaml

CI will probably fail as https://github.com/robotology/whole-body-estimators/pull/135 still needs to be merged and released, but better to open this PR so we can check if we are missing some release.

Update package versions in 2021.11.1 release

---

CHANGELOG.md
cmake/BuildYARP.cmake

The `usbCamera` device is a useful YARP device even for developers on their laptops that want to stream the output of their webcam on a YARP port. For this reason, it make sense to enable its compilation even if `ROBOTOLOGY_ENABLE_ICUB_HEAD` is OFF.

BuildYARP: Enable compilation of usbCamera YARP device even if ROBOTOLOGY_ENABLE_ICUB_HEAD is OFF

---

.github/workflows/ci.yml
CHANGELOG.md
apt.txt
doc/conda-forge.md
doc/deprecated-installation-methods.md
doc/vcpkg-dependencies.md

This modification is done to that yarpviz is automatically https://github.com/robotology/robotology-superbuild/issues/987 . This just modifies the documentation, but on the conda side graphviz would still not be found (and so `yarpviz` not build) until https://github.com/robotology/ycm/pull/389 is merged.
However I think that we can merge this PR without waiting for https://github.com/robotology/ycm/pull/389 . Then, as soon as https://github.com/robotology/ycm/pull/389 is merged, yarpviz will start being compiled also in conda builds.

Add graphviz dependency to the superbuild

---

.github/workflows/ci.yml

For some reason `ROBOTOLOGY_USES_PYTHON` was still disabled on Windows/Conda. Furthemore, there was a reference to https://github.com/robotology/robotology-superbuild/issues/563, but `ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS` was enabled in CI since a long time. So I cleanup up a bit this part of the CI scripts, eliminating also some debug `cat` commands

GitHub Actions: Cleanup CMake conda configuration

---

cmake/ProjectsTagsStable.cmake

`ICUB_TAG` was set to 1.22.0 in https://github.com/robotology/robotology-superbuild/pull/979 for yarp-3.5 compatibility, but this is not necessary anymore since https://github.com/robotology/robotology-superbuild/pull/984 . However, in https://github.com/robotology/robotology-superbuild/pull/984 we forgot to remove the `ICUB_TAG` hardcoding.

Do not set ICUB_TAG in ProjectsTagsStable

---

.github/workflows/ci.yml
doc/conda-forge.md

To avoid duplicate the number of jobs, on Windows we compile against Visual Studio 2022 for Stable branches, and against Visual Studio 2019 for Unstable branches.

Add support for Visual Studio 2022 in CI and Documentation

---

.ci/install_debian.sh
.github/workflows/ci.yml

Let's add Ubuntu Jammy (22.04) to the CI to ensure that there are no problems once it is released, as it is the next Ubuntu LTS to which most users will eventually upgrade. For now a small workaround is necessary, that probably will stop being necessary once `libgazebo-dev` is updated to depend on `libsdformat9-dev`.

Add ubuntu:jammy to docker-based CI

---

.github/workflows/ci.yml
apt.txt
cmake/BuildYARP.cmake
doc/conda-forge.md

Since a long time, we enabled the `YARP_USES_I2C` option on YARP. The option is automatically disabled if I2C is not found (and this is convenient for us on macOS and Windows), but the problem is that we never installed the required dependency. This PR fixes the problem by installing `libi2c-dev` from apt and `libi2c` from conda-forge.
Fix https://github.com/robotology/robotology-superbuild/issues/999 .
Fix https://github.com/robotology/robotology-superbuild/issues/1002 .

Document installation of libi2c in Linux with apt and conda

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

This is part of the work on branch https://github.com/traversaro/robotology-superbuild/tree/fix727 that was done to solve https://github.com/robotology/robotology-superbuild/issues/727 . However, this part can be contributed on its own PR.
This PR bumps the qhull and CppAD version to track the latest version. In particular, this ensures that the versions used in the superbuild are compatible with the latest versions used in conda-forge:
* https://github.com/conda-forge/qhull-feedstock
* https://github.com/conda-forge/cppad-feedstock
Note that qhull has a bit of a complex versioning scheme, as it has releases like `8.0.2`  and `2020.2` . We switch to the `2020.2`-style tags for compatibility with most linux distros (see https://repology.org/project/qhull/versions) and with conda-forge.
As …

Bump qhull and CppAD to latest versions

---

.github/workflows/ci.yml

The issue described in https://github.com/robotology/robotology-superbuild/issues/1020 is taking some time to be fixed upstream, so for the time being let's just use a old `Mambaforge` that is known to work.

Pin miniforge version to avoid mamba regression

---

.github/workflows/icubTechIIT_code.yml

It now sends just the new released version, this is needed for an internal refactoring of `icub-tech-iit/code` actions

[code trigger]: changed the repository dispatch

---

.github/workflows/ci.yml
CHANGELOG.md
doc/cmake-options.md
doc/deprecated-installation-methods.md

See https://github.com/robotology/robotology-superbuild/issues/1017#issuecomment-1038960278 for a rationale on this choice.
Fix https://github.com/robotology/robotology-superbuild/issues/1017 .

Document that ROBOTOLOGY_USES_GAZEBO is not supported on macOS with Homebrew dependencies

---

.github/workflows/ci.yml
conda/conda_build_config.yml
doc/conda-forge.md

It is a workaround for https://github.com/conda-forge/gazebo-feedstock/issues/119 like https://github.com/robotology/robotology-superbuild/pull/1022, but I like it more because it is more explicit. Furthermore, I also adding it in the CI that I forgot in https://github.com/robotology/robotology-superbuild/pull/1022 .

Conda: Specify explicitly requirement of qt=5.12.9=*_4

---

.github/workflows/ci.yml

Revert https://github.com/robotology/robotology-superbuild/pull/1026 as now the latest release of miniforge seems to be working as expected.

Restore latest miniforge

---

.github/workflows/ci.yml
conda/conda_build_config.yml
doc/conda-forge.md

Workaround for https://github.com/robotology/robotology-superbuild/issues/1032 while we wait for:
* https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6985
* https://github.com/dcnieho/FreeGLUT/pull/96
* https://github.com/conda-forge/freeglut-feedstock/pull/31
To be merged and released.

Pin cmake to 3.21 to workaround FindGLUT regression

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

Workaround for https://github.com/robotology/robotology-superbuild/issues/1033 . This can be reverted once https://github.com/robotology/event-driven/pull/153 is merged.

Pin  event-driven to v1.6 to fix macOS CI

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

Revert https://github.com/robotology/robotology-superbuild/pull/1038 as https://github.com/robotology/event-driven/pull/153 has been merged.

Unpin event-driven repo

---

.github/workflows/generate-conda-packages.yaml
.github/workflows/release.yml
CHANGELOG.md
cmake/Buildcasadi.cmake
cmake/Buildmanif.cmake
conda/cmake/CondaGenerationOptions.cmake
conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake
conda/metapackages_recipes_template/robotology-distro-all.yaml
conda/metapackages_recipes_template/robotology-distro.yaml
conda/python/generate_conda_recipes_from_metametadata.py
scripts/robotologyBumpCondaBuildNumber.sh

This PR adds the logic to generate the `robotology-distro` and `robotology-distro-all` conda metapackages for each new robotology-superbuild. 
This would permit user to run:
~~~
mamba install -c conda-forge -c robotology robotology-distro=2022.0 yarp icub-main idyntree
~~~
And the solver will automatically compute the correct version of `yarp`, `icub-main` and `idyntree` to install. Note that `robotology-distro` will just constrain the version of packages that are installed by the user, so installing just that package will not install anything else. On the other hand, this PR also adds the `robotology-distro-all` metapackage, that will install all the packages contained in the robotology-superbuild corresponding to a given release.
No documentation is currently added as I prefer to …

Add generation of conda metapackages robotology-distro and robotology-distro-all for each new distro release

---

releases/latest.releases.yaml
scripts/robotologyUpdateLatestReleases.sh

This matches the latest available version on conda-forge: https://anaconda.org/conda-forge/cppad .
Furthermore, I remove `CppAD` to the list of repos that we do not automatically update: as it is important that we track the same version that it used in conda-forge (and there the latest version is tipically adopted quite quickly as the process is automatic, see https://github.com/conda-forge/cppad-feedstock/pull/13) then it is better to update the version as soon as it is available.
Furthermore, I also removed `event-driven` from the list of repos that we do not update as a recent release is now available for it, and I just noticed this when I removed CppAD.

Bump CppAD to 20220000.2 and let CppAD be updated by automatic update

---

.github/workflows/generate-conda-packages.yaml
conda/cmake/CondaGenerationOptions.cmake
conda/conda_build_config.yml

The pin was added in https://github.com/robotology/robotology-superbuild/pull/1025 to avoid any problem related to https://github.com/conda-forge/gazebo-feedstock/issues/119 . Anyhow, this is creating problems in macOS, so add two further pins and disable the metapackage generation.

macOS conda package generation: Pin gazebo and opencv and do not generate metapackages

---

.github/workflows/ci.yml
conda/conda_build_config.yml
doc/conda-forge.md

Revert https://github.com/robotology/robotology-superbuild/pull/1035 as now CMake 3.22.3 has been released with the fix https://gitlab.kitware.com/cmake/cmake/-/commit/44f7238d5d542afac860be928fa215c0f3f9a8fb so we can solve https://github.com/robotology/robotology-superbuild/issues/1032 without workarounds (see https://github.com/Kitware/CMake/blob/v3.22.3/Modules/FindGLUT.cmake).

Unpin CMake

---

doc/cmake-options.md

Added the link to the operating system-specific installation documentation in the sections 'System Dependencies'.

Updated link for OS specific installation

---

cmake/BuildYARP.cmake

We already depend on opencv and this device is quite useful, so it make sense to enable it.

BuildYARP: Enable compilation of opencv_grabber YARP device

---

cmake/Buildicub-models.cmake

After the change of options in https://github.com/robotology/icub-models/pull/143

Fix support for Python bindings in icub-models

---

CHANGELOG.md
cmake/RobotologySuperbuildOptions.cmake
conda/cmake/CondaGenerationOptions.cmake
packaging/windows/CMakeLists.txt
releases/2022.02.1.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1079 . Bump YCM to 0.13.1 to fix CMake 3.23 compatibility.

Create 2022.02.1 release

---

.github/workflows/ci.yml
apt.txt
doc/conda-forge.md

This should fix https://github.com/robotology/robotology-superbuild/issues/1008

Update Conda documentation - add Soxr dependency

---

cmake/BuildYARP.cmake

As the unstable branches contain the fix  https://github.com/robotology/yarp/pull/2810 .
FYI @S-Dafarra

BuildYARP: Set ENABLE_yarpcar_mjpeg to ON on Apple if we are using Unstable branches

---

cmake/BuildYARP.cmake

Workaround for fixing https://github.com/robotology/robotology-superbuild/issues/1090 until https://github.com/robotology/yarp/pull/2822 is fixed and released.

BuildYARP: Enable YARP_DISABLE_MACOS_BUNDLES option to restore compatibility with CMake 3.23.1 on macOS

---

cmake/ProjectsTagsStable.cmake
releases/latest.releases.yaml

After the recent release https://github.com/robotology/ycm/releases/tag/v0.14.0 .

Bump YCM to 0.14

---

.ci/install_debian.sh
.github/workflows/ci.yml
doc/cmake-options.md

The problems described in https://github.com/robotology/robotology-superbuild/issues/944 should now be solved. 
This is also related to https://github.com/robotology/robotology-superbuild/issues/1095 .
Also do a general cleanup of CI in view of Ubuntu 22.04 release, and close or remove workaround due:
* https://github.com/robotology/robotology-superbuild/issues/494
* https://github.com/robotology/robotology-superbuild/pull/998
* https://github.com/robotology/robotology-superbuild/pull/593
* https://github.com/robotology/robotology-superbuild/issues/384
* https://github.com/robotology/robotology-superbuild/pull/593
This PR also completes the documentation for Ubuntu 22.04 by updating the docs to address https://github.com/robotology/robotology-superbuild/issues/1095 and adding a workaround …

CI: Enable Gazebo in all apt jobs and enable Ubuntu Jammy 22.04 and Debian Bullseye 11 Job

---

apt-python.txt

After https://github.com/robotology/robotology-superbuild/pull/1069 the CI was failing on some configurations with error (https://pipelines.actions.githubusercontent.com/serviceHosts/b3e4f43b-711e-4c4a-9229-829950399fe6/_apis/pipelines/1/runs/3570/signedlogcontent/11?urlExpires=2022-04-27T06%3A48%3A33.9360011Z&urlSigningMethod=HMACV1&urlSignature=7DvePC4jZNepFYPr7u0BjV3Xw%2BIr8xd8mznaRQcwy9I%3D):
~~~
2022-04-27T02:48:24.1609768Z [91/368] Performing install step for 'meshcat-python'
2022-04-27T02:48:24.1610645Z FAILED: src/meshcat-python/CMakeFiles/YCMStamp/meshcat-python-install 
2022-04-27T02:48:24.1612294Z cd /__w/robotology-superbuild/robotology-superbuild/build/src/meshcat-python && /usr/bin/python3.9 -m pip install --upgrade --no-deps …

Add python3-pip apt package dependency

---

cmake/Buildrobot-log-visualizer.cmake
conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake
conda/pure_python_recipe_template/meta.yaml
doc/developers-faqs.md

This should permit to correctly support executables created by `entry_points` in Python packages.
Furthermore, add the `robot-log-visualizer = robot_log_visualizer.__main__:main` entry_point for `robot-log-visualizer`. 
Fix https://github.com/robotology/robotology-superbuild/issues/1105.

Add support for <pkgName>_CONDA_ENTRY_POINTS to specify build/entry_points option in conda meta.yaml file

---

apt.txt

I'm trying to build the `v2021.11.0` tag of the superbuild in a clean docker image with the following command:
```dockerfile
RUN git clone -b ${SUPERBUILD_TAG} https://github.com/robotology/robotology-superbuild &&\
cd robotology-superbuild &&\
sudo bash ./scripts/install_apt_dependencies.sh &&\
sudo rm -rf /var/lib/apt/lists/*
RUN cd robotology-superbuild &&\
cmake -S . -B build \
-GNinja \
-DNON_INTERACTIVE_BUILD:BOOL=ON \
-DYCM_DISABLE_SYSTEM_PACKAGES:BOOL=ON \
-DROBOTOLOGY_USES_GAZEBO:BOOL=ON \
-DROBOTOLOGY_USES_MATLAB:BOOL=ON \
-DROBOTOLOGY_USES_PYTHON:BOOL=ON \
-DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=ON \
-DROBOTOLOGY_ENABLE_HUMAN_DYNAMICS:BOOL=ON \
-DROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS:BOOL=ON \
&&\
cmake --build build/ &&\
find build/src/ -type f -not -name 'CMakeCache.txt' -delete
``` …

Add missing Ubuntu 20.04 apt dependencies

---

cmake/ProjectsTagsStable.cmake
releases/latest.releases.yaml

YARP 3.7.0 was released recently: https://github.com/robotology/community/discussions/579 .

Switch PROJECT_TAGS Stable to use YARP 3.7

---

cmake/Buildrobot-log-visualizer.cmake
conda/pure_python_recipe_template/meta.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1122 .

Add setuptools-scm dependency in pure python conda template and pyqtwebengine to robot-log-visualizer conda dependencies

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

For consistency with conda-forge: https://github.com/conda-forge/cppad-feedstock/pull/16 .

Bump CppAD version to 20220000.4

---

cmake/Buildmeshcat-python.cmake
cmake/RobSupPurePythonYCMEPHelper.cmake

This should help to avoid problems such as the one described in https://github.com/robotology/robotology-superbuild/issues/1118 . The only downside is that during the first installation the packages are not installed, so the log will contain bogus warnings such as:
~~~
[ 71%] Skipping update step for 'pyqtconsole'
[ 71%] Performing configure step for 'pyqtconsole'
cmake version 3.22.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
[ 71%] Performing build step for 'pyqtconsole'
WARNING: Skipping pyqtconsole as it is not installed.
[ 71%] Performing install step for 'pyqtconsole'
Processing /home/straversaro/robotology-superbuild/src/pyqtconsole
Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyqtconsole
Building wheel for pyqtconsole …

Always uninstall pure Python packages every time they are installed

---

.github/workflows/matlab-one-line-install-test.yml

@FabioBergonti experiened problems in using a similar script to what describe in https://github.com/robotology/robotology-superbuild/blob/master/doc/matlab-one-line-install.md in CI, so better to test it at the source.

Add test for MATLAB one line installer

---

scripts/install_robotology_packages.m

Now that mamba is more stable, it should ensure a faster installation of packages.

Switch MATLAB one-line install to mamba (take two)

---

.github/workflows/matlab-one-line-install-test.yml

Workaround for https://github.com/robotology/robotology-superbuild/issues/1159 .

Switch to ubuntu-22.04 for workaround of matlab one line install job

---

apt-python.txt

Backport of https://github.com/robotology/robotology-superbuild/pull/1164 for 2022.05.2 release.

Add libqt5multimedia5-plugins to apt-python.txt (2022.05 backport)

---

apt-python.txt

As it is required by robot-log-visualizer, see https://github.com/robotology/robotology-superbuild/issues/1163 .

Add libqt5multimedia5-plugins to apt-python.txt

---

.github/workflows/ci.yml
doc/conda-forge.md

graphviz 4 have a breaking change that will be reverted in a following release (see https://github.com/robotology/robotology-superbuild/issues/1152), so it does not make sense to try to be compatible with graphviz 4 at this moment.

Switch to graphviz 2.50 to avoid compilation problems

---

.github/workflows/generate-conda-packages.yaml
cmake/BuildYARP.cmake

As https://github.com/conda-forge/staged-recipes/pull/18234 will hopefully be soon merged, we can finally fix https://github.com/robotology/robotology-superbuild/issues/752 and https://github.com/robotology/robotology-superbuild/issues/1094 .
In general, the changes are similar to https://github.com/robotology/robotology-superbuild/pull/807 but for YARP.

Switch to use YARP conda-forge binary package when generating conda packages

---

apt.txt

It is a YARP dependency that was missing from `apt.txt`

apt.txt: add libsqlite3-dev

---

cmake/RobotologySuperbuildOptions.cmake
conda/cmake/CondaGenerationOptions.cmake
packaging/windows/CMakeLists.txt
releases/2022.05.2.yaml

The `2022.05.2.yaml` file for now is copied from `2022.05.1.yaml`, so other changes are clearly tracked.

Prepare for 2022.05.2 release

---

releases/2022.05.2.yaml

This should fix the failure reported in https://github.com/robotology/robotology-superbuild/pull/1180#issuecomment-1162274510 .

2022.05.2 : Bump `yarp@v3.7.1`, `icub-firmware-shared@v1.25.1`

---

cmake/BuildmatioCpp.cmake

Otherwise matio-cpp will be compiled without Eigen support, see https://github.com/ami-iit/matio-cpp/blob/ed9b196360b8083c3eccd3348afa7969d3a4f1fa/CMakeLists.txt#L94 .

conda: Add eigen as dependency of matio-cpp

---

.github/workflows/generate-conda-packages.yaml

This versions were pinned to workaround problems with older versions, but now everything should be working fine. 
Fix https://github.com/robotology/robotology-superbuild/issues/1061 .
This PR builds on top of https://github.com/robotology/robotology-superbuild/pull/1170, so it first requires that one to be merged before.

Do not pin multisheller, mamba and boa versions in Generate Conda Packages CI jobs

---

.github/workflows/ci.yml

The only relevant job for this branch is `Default`, that tests the `2022.05.2.yaml` release.

Remove Unstable and LatestReleases jobs from releases/2022.05 CI

---

releases/2022.05.2.yaml

As per the title.
<sub>I mistakenly called the branch referring to v1.16.1</sub>

Update `icub-main` to `v1.26.1`

---

CHANGELOG.md
cmake/RobotologySuperbuildOptions.cmake
doc/cmake-options.md

For a long time, `ROBOTOLOGY_USES_GAZEBO` was set to `OFF` on Windows as Gazebo was either not available or experimental. As Gazebo on Windows is now quite stable, leaving the option to OFF is creating more problems than it solves.

Enable by default ROBOTOLOGY_USES_GAZEBO also on Windows

---

cmake/RobotologySuperbuildOptions.cmake

The option is not supported on Windows as the repo https://github.com/robotology/event-driven is not supported on Windows, so do now expose the `ROBOTOLOGY_ENABLE_EVENT_DRIVEN` option on Windows to avoid that users enable it.

Do not show the ROBOTOLOGY_ENABLE_EVENT_DRIVEN option on Windows

---

.github/workflows/ci.yml

This PR to remove the workaround https://github.com/robotology/robotology-superbuild/pull/1143 for the HUMAN_DYNAMICS profile as https://github.com/robotology/yarp-devices-forcetorque/issues/31 has been closed.

Re-enable HUMAN_DYNAMICS in Unstable branches

---

cmake/BuildICUB.cmake

It has been added here https://github.com/robotology/icub-main/pull/813

BuildICUB: add canBusFtSensor device for icub-head profile

---

.github/workflows/ci.yml
doc/conda-forge.md

This was added in https://github.com/robotology/robotology-superbuild/pull/1166 . Now that graphviz 5 was released and the conda-forge related migration is almost completed, I think we can remove the workaround: https://conda-forge.org/status/#graphviz5 .

Remove graphviz=2.5 workaround

---

cmake/RobotologySuperbuildOptions.cmake
doc/change-project-tags.md

Fix https://github.com/robotology/robotology-superbuild/issues/1226 .
cc @marcoaccame @mfussi66 @valegagge @davidetome @triccyx

Make ROBOTOLOGY_PROJECT_TAGS and ROBOTOLOGY_PROJECT_TAGS_CUSTOM_FILE non advanced CMake options and update docs

---

conda/pure_python_recipe_template/meta.yaml

I noticed that in https://github.com/robotology/robotology-superbuild/runs/8082454197 a lot of time is spent to build multiple versions of `robot-log-visualizer`, even if a single version is sufficient to work fine on all python versions. This can be force with `noarch: python`, see https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages .

Specify that recipes built from pure_python_recipe_template are noarch

---

CHANGELOG.md
CMakeLists.txt
cmake/template/setup.sh.in
doc/environment-variables-configuration.md

`XDG_DATA_DIRS` default value (at least on Linux system) when the variable is not set is `/usr/local/share/:/usr/share/`, see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html . This means that the behaviour of the Linux application when `XDG_DATA_DIRS` is not set or when it is set to an empty string is not the same, as in the latter case the directories `/usr/local/share/:/usr/share/`, where most configuration files of system installed software are installed are ignored, resulting in software not working properly (see https://github.com/robotology/robotology-superbuild/issues/1187 for some examples).
On most system this issue was not appearing as some other system installed software was already properly defining `XDG_DATA_DIRS` with …

Fix Linux bug when XDG_DATA_DIRS is not defined

---

cmake/BuildICUB.cmake

This is required for iCubGenova09

Enable embObjMultipleFTsensors in icub-main if ROBOTOLOGY_ENABLE_ICUB_HEAD is ON

---

doc/install-mambaforge.md

This PR to add a link to an issue in order to fix broken Command Prompt on Windows when the uninstall steps are not followed.
It happened to me and it fixed the issue.
cc @S-Dafarra @traversaro

Add recovery step from dirty mambaforge uninstall on Windows

---

.github/workflows/generate-conda-packages.yaml

Currently the macOS conda package generation job is failing in a non-deterministic way with a Segmentation fault, using an old version of liblief seems to work fine in avoiding this problem.
See https://github.com/conda-forge/conda-forge.github.io/issues/1823#issuecomment-1239926891 .
Workaround for https://github.com/robotology/robotology-superbuild/issues/1250 .

Install old version of liblief to avoid macOS conda build crash

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1271 . 
The problem occured in https://github.com/robotology/robotology-superbuild/issues/1271 is due to a missing header that was solved upstream in https://github.com/artivis/manif/pull/248 , however there was no release since then, and for the superbuild from source we still rely on our manif fork at https://github.com/robotology-dependencies/manif. For this reason, I backported https://github.com/artivis/manif/pull/248 on our fork, and release 0.0.4.2 release. This PR just bumps the manif version used to 0.0.4.2 , solving https://github.com/robotology/robotology-superbuild/issues/1271 .

Bump manif fork to 0.0.4.2

---

cmake/Buildbipedal-locomotion-framework.cmake
cmake/RobotologySuperbuildLogic.cmake
doc/conda-forge.md
doc/deprecated-installation-methods.md
doc/vcpkg-dependencies.md

See https://github.com/robotology/robotology-superbuild/issues/1269#issuecomment-1257811559 . Basically, if we install PCL with a package manager, we now install only qhull, so we would have both qhull installed and the one compiled by the superbuild. On macOS|homebrew, Windows|vcpkg and conda there is no problem with the installed qhull, so we switch to just use the qhull installed by the package manager. 
To do that also on Ubuntu with apt dependencies, we would need to drop Ubuntu 20.04 , that I am afraid it will not happen anytime soon.

Only build qhull on Linux with apt dependencies

---

conda/cmake/RobotologySuperbuildGenerateCondaRecipes.cmake
conda/conda_build_config.yml

Fix https://github.com/robotology/robotology-superbuild/issues/1276 .

Correctly generate conda packages for packages that depend on vtk

---

.github/workflows/ci.yml

We already build as Release on Windows/conda, so to early catch Debug problems (such as https://github.com/robotology/robotology-superbuild/issues/1252) we compile Debug on Windows/vcpkg.

Build as Debug by default on Windows/vcpkg

---

cmake/RobotologySuperbuildOptions.cmake

The option was meant to be set by default to off (see docs https://github.com/robotology/robotology-superbuild/blob/8ce7ee0344f1ee76fe4affa6d4089e229ab02a3c/doc/cmake-options.md#dependencies-cmake-options). Setting it by default to ON was just a copy and paste error introduced in https://github.com/robotology/robotology-superbuild/pull/1217 .

Set ROBOTOLOGY_USES_PCL_AND_VTK by default to OFF

---

releases/latest.releases.yaml

This PR reverts the wrongly assigned version to `icub-models` (ref. #1280) and advances the version of `icub-firmware-models` (as it was originally intended).

Fix #1280 and bump `icub-firmware-models@v1.26.0`

---

.github/workflows/generate-conda-packages.yaml
.github/workflows/icubTechIIT_code.yml

`set-output` is now deprecated as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

[CI]: Replaced `set-output`

---

scripts/robotologyGitStatus.sh

As per title. This will help to automatically store the status of each repo contained in the superbuild

Add git diff in robotologyGitStatus script

---

.github/workflows/ci.yml
doc/conda-forge.md

This should solve a problem that @lrapetti had in which following the instructions will result in an old Gazebo affected by a critical bug (https://github.com/conda-forge/gazebo-feedstock/pull/152).

Unify step of installation of conda-forge robotology-superbuild dependencies

---

.github/workflows/ci.yml
doc/cmake-options.md

Workaround until https://github.com/robotology/robotology-superbuild/issues/1298 is fixed.

Pin Python to 3.10 on conda-forge until the issue with 3.11 is fixed

---

.github/workflows/ci.yml
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
doc/cmake-options.md
releases/latest.releases.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1298
Revert https://github.com/robotology/robotology-superbuild/pull/1299

Fix issue of manif fork with Python 3.11 and revert pinning of Python 3.10

---

cmake/Buildbipedal-locomotion-framework.cmake

Workaround for https://github.com/robotology/robotology-superbuild/issues/1307, to get the Stable branches to compile fine.

Disable blf's YarpRobotLoggerDevice  compilation on macOS and Windows

---

cmake/BuildICUB.cmake

Workaround for:
* https://github.com/robotology/icub-main/issues/842
* https://github.com/robotology/robotology-superbuild/issues/1307

Disable iCub_SIM compilation for Unstable branches

---

.github/workflows/ci.yml

Revert https://github.com/robotology/robotology-superbuild/pull/1305
Fix https://github.com/robotology/robotology-superbuild/issues/1303

Re-enable ROBOTOLOGY_ENABLE_TELEOPERATION and ROBOTOLOGY_ENABLE_HUMAN_DYNAMICS with Unstable branches

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

This is to ensure that `pip list` lists the casadi package installed by the superbuild, see:
* https://github.com/casadi/casadi/pull/2878
* https://github.com/ami-iit/casadi/pull/1
Actually fixes (even if for some reason we already closed it) https://github.com/robotology/robotology-superbuild/issues/1012 .

Bump casadi to 3.5.5.4

---

.github/workflows/ci.yml

Workaround for https://github.com/robotology/robotology-superbuild/issues/1321 . 
I prefer to avoid working on Homebrew this days, but unfortunatly GitHub Action upstream is taking some time to address this, so it is better to have some dirty workaround to avoid the noise of build failures.

Add workaround for breakage of brew upgrade in GitHub Actions

---

.github/workflows/ci.yml
doc/conda-forge.md

Workaround for https://github.com/robotology/robotology-superbuild/issues/1328 .

Pin conda-forge's opencv to <= 4.6 until bipedal-locomotion-framework supports it

---

cmake/BuildYARP.cmake

Since YARP 3.8 the YARP_COMPILE_ALL_FAKE_DEVICES is used to enable all the fake devices, see https://github.com/robotology/yarp/pull/2940 . We enable it to make sure that fake devices are enabled in the superbuild build of YARP.

BuildYARP: Enable new CMake option YARP_COMPILE_ALL_FAKE_DEVICES

---

cmake/BuildICUB.cmake

**What's new:**
- This change enables the POS service by default when building the `robotology-superbuild` with ICUB_HEAD=ON. The `POS` service is mandatory to be able to read the absolute encoders mounted on `ergoCub's` hands. 
**Notes:**
- Other robots are not affected by this change

Enable the POS service by default when ICUB_HEAD in enabled

---

README.md

In particular:
* Just document WSLg to run graphical applications as not it is available also on Windows 10
* Do not document anymore WSL1 as it is not really widely used, and it is not worth to document it (any user expert enough to run WSL1 will be able to configure its system appropriately)
Fix https://github.com/robotology/robotology-superbuild/issues/1190 .

Simplify WSL docs

---

.github/workflows/ci.yml
doc/conda-forge.md

Until conda-forge fully migrates to libjpeg-turbo (see https://github.com/conda-forge/conda-forge.github.io/issues/673), we should install the old plan jpeg library.
Fix https://github.com/robotology/robotology-superbuild/issues/1344 .

Install jpeg until conda-forge is migrated to libjpeg-turbo

---

cmake/BuildYARP.cmake
cmake/RobotologySuperbuildOptions.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/1341 .
This PR only adds the minimal logic for the `ROBOTOLOGY_USES_CSHARP` option, and it marks it is as advanced so that it is hidden by default. The steps for making this option fully supported are described in https://github.com/robotology/robotology-superbuild/issues/1347. As nobody that I am collaborating with is using C#, I will not look into this, but contribution from the community in form of Pull Request will be welcome.

Add advanced CMake option ROBOTOLOGY_USES_CSHARP to enable compilation of C# bindings on YARP

---

.github/workflows/ci.yml
doc/conda-forge.md

Temporary workaround for https://github.com/robotology/robotology-superbuild/issues/1366 at least for conda-forge, while on homebrew we can't pin software to older versions.

Avoid cmake 3.26 when installing dependencies from conda-forge

---

.github/workflows/generate-conda-packages.yaml
cmake/BuildGazeboYARPPlugins.cmake
conda/cmake_recipe_template/build.sh
conda/cmake_recipe_template/meta.yaml

See https://github.com/robotology/robotology-superbuild/issues/752 for the more generic issue.
To be merged only once https://github.com/conda-forge/staged-recipes/pull/21891 is merged.

Use gazebo-yarp-plugins package from conda-forge instead of building  a specific one for robotology conda channel

---

.github/workflows/ci.yml

The ubuntu-18.04  GitHub Actions image has been removed (see https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/), so we can just remove the related jobs from the CI. Note that anyhow we still have Ubuntu 18.04 CI coverage (see https://github.com/robotology/robotology-superbuild/issues/481) thanks to the Docker bionic CI job.
Furthermore, I added the n-th workaround for Homebrew CI, to fix https://github.com/robotology/robotology-superbuild/issues/1383 .

Remove jobs on ubuntu-18.04 and add Homebrew workaround

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

Until https://github.com/robotology/robotology-superbuild/pull/1379 is correctly merged, let's make sure that we use the correct version of casadi 3.5.* .

Correctly fix casadi and casadi-matlab-bindings TAG

---

.github/workflows/ci.yml

https://github.com/ami-iit/bipedal-locomotion-framework/pull/643 still needs to be released, so for the time being just install an old CMake version to ensure that also the LatestRelease job is not failing.

Add workaround for CMake 3.26.1 issue

---

cmake/Buildbipedal-locomotion-framework.cmake
cmake/Fetchonnxruntimebinaries.cmake

Just when `ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS` is enabled, when we are on Linux and we are not using Conda, this PR adds support for the upcoming `FRAMEWORK_USE_onnxruntime` option of bipedal-locomotion-framework (see https://github.com/ami-iit/bipedal-locomotion-framework/pull/652).
Differently from most other dependencis handled by the robotology-superbuild, given its size and the time necessary to compile, in this case we do not compile onnxruntime from scratch, but rather we download its binaries at configuration time, and we install them. We do this just on Linux and when conda is not used.
This is just meant to be an initial test. If this binaries create problems of incompatibility with other libraries installed by apt, we will need to find another solution. Instead, for …

Add support for onnxruntime just on Linux with apt

---

cmake/Buildcasadi.cmake

Fix comment reported in https://github.com/robotology/robotology-superbuild/issues/1378#issuecomment-1510960702 . In our fork of casadi 3.5.5 the option by default was ON (see https://github.com/ami-iit/casadi/pull/1/files#diff-75df003c8ca5bb396ddc7edb9b4b18685f77e287feaa44b6c9175d1a46364275R168), so we never did this at the superbuild level, however this is required now that we are using the upstream version after it was merged in https://github.com/casadi/casadi/pull/2878 .

Buildcasadi: Enable CASADI_PYTHON_PIP_METADATA_INSTALL option

---

.github/workflows/ci.yml
doc/cmake-options.md

Fix https://github.com/robotology/robotology-superbuild/issues/1392 .

Disable ROBOTOLOGY_ENABLE_EVENT_DRIVEN on Ubuntu Bionic and Debian Buster

---

cmake/Buildcasadi.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

Bump CasADi to 3.6.2 . Note that fortunatly after:
* https://github.com/casadi/casadi/pull/3150
* https://github.com/casadi/casadi/pull/3149
have been merged, from 3.6.3 we can switch to use the official CasADi releases instead of our fork.

Bump CasADi to 3.6.2

---

cmake/BuildYARP.cmake

Remove workarounds related to https://github.com/robotology/robotology-superbuild/issues/377 .

Remove workaround related to YARP_USE_SYSTEM_SQLite problems in macOS with Homebrew

---

.github/workflows/ci.yml
doc/conda-forge.md

Fix workaround introduced to fix https://github.com/robotology/robotology-superbuild/issues/1366 .

Remove workarounds related to CMake 3.26

---

cmake/BuildiDynTree.cmake

This is an hack due to the fact that iDynTree 9 will not support IDYNTREE_USES_IRRLICHT  on Ubuntu 18.04 . Hopefuly we can soon remove this once https://github.com/robotology/robotology-superbuild/issues/481 is fixed.

iDynTree: Do not pass IDYNTREE_USES_IRRLICHT if glfw3 is not found

---

.github/workflows/ci.yml
CHANGELOG.md
CMakeLists.txt
README.md
doc/cmake-options.md
doc/deprecated-installation-methods.md
doc/developers-faqs.md
doc/environment-variables-configuration.md
doc/install-mambaforge.md
doc/unsupported-homebrew-installation.md

As announced in https://github.com/robotology/robotology-superbuild/issues/842#issuecomment-1500326241, this PR removes Homebrew support and documentation.

Disable Homebrew from CI and do not support it anymore

---

cmake/Buildmanif.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

See https://github.com/artivis/manif/issues/274 . This is only useful once https://github.com/robotology-dependencies/manif/pull/2 is merged and a new version is tagged, but I already open the PR to collect early feedback.

Buildmanif: Explicitly compile with C++17

---

.github/workflows/ci.yml
apt.txt
cmake/BuildYARP.cmake
doc/conda-forge.md
doc/unsupported-homebrew-installation.md
doc/vcpkg-dependencies.md

This PR enable in YARP the CMake options to ensure that the following portmonitor are enabled:
* `bottle_compression_zlib`
* `depthimage_compression_zlib`
* `image_compression_ffmpeg`
These portmonitors are already used by the HSP team working on ergocub (fyi @andrearosasco) and can be useful for anyone sending big amount of data over a YARP network (@S-Dafarra @GiulioRomualdi @mebbaid @davidegorbani).
This PR also adds the required dependencis (ffmpeg and zlib) to the dependency of the superbuild. This was already discussed in https://github.com/robotology/robotology-superbuild/issues/1071, but we decided not to proceed as some devices in YARP (`ffmpeg_grabber` and `ffmpeg_writer`) were not compatible with ffmpeg 5. However, it turns out that `image_compression_ffmpeg` can be used and …

YARP: Enable compilation of bottle_compression_zlib, depthimage_compression_zlib and image_compression_ffmpeg portmonitors

---

cmake/BuildOsqpEigen.cmake

Requires https://github.com/robotology/osqp-eigen/pull/145 .
Fix https://github.com/robotology/robotology-superbuild/issues/1451 .

Explicitly pass OSQP_IS_V1 option to osqp-eigen to avoid problems in vcpkg/Debug corner case

---

.ci/install_debian.sh

In https://github.com/robotology/robotology-superbuild/pull/1416 we dropped support for ROBOTOLOGY_USES_GAZEBO on Ubuntu 18.04, but we still were installing Gazebo on 18.04, that recently is causing problems: https://github.com/robotology/robotology-superbuild/issues/1457 . In this PR we stop also installing Gazebo on Ubuntu 18.04, that hopefully should fix https://github.com/robotology/robotology-superbuild/issues/1457 .

Do not install Gazebo on Ubuntu 18.04

---

.github/workflows/matlab-one-line-install-test.yml
doc/cmake-options.md
doc/matlab-one-line-install.md

Fix https://github.com/robotology/robotology-superbuild/issues/1461 . In https://github.com/robotology/robotology-superbuild/pull/1462/commits/f8f31010f81f54d8fd14b5d28985d487c78e110e I also document this in the documentation.

Only test and document official compatibility of MATLAB binary packages with MATLAB >= R2022a

---

README.md
doc/cmake-options.md
doc/matlab-one-line-install.md

Fix https://github.com/robotology-legacy/codyco-superbuild/issues/141
Fix https://github.com/robotology/robotology-superbuild/issues/38
Fix https://github.com/robotology/robotology-superbuild/issues/64

Add documentation on how to solve "Invalid MEX-file error"  when using MATLAB

---

.github/workflows/ci.yml

Fix https://github.com/robotology/robotology-superbuild/issues/1466 .

Pin actions/checkout to v3.6.0 for Ubuntu 18.04 compatibility

---

.github/workflows/ci.yml

Fix https://github.com/robotology/robotology-superbuild/issues/1472 by deleting unused directories (from https://github.com/apache/flink/blob/53702736382b80fa905494e69654061a84741e84/tools/azure-pipelines/free_disk_space.sh#L48C1-L53C40) in the host machine. Given that we had this problem in actions that are running in a contained, we had first to mount the folder that contained the files to delete in the container.

GitHub Actions: Free disk space to avoid out of disk space errors

---

.github/workflows/ci.yml
README.md
scripts/install_robotology_packages.m

Fix https://github.com/robotology/idyntree/issues/1109 .

Use netlib libblas on macOS to avoid openmp conflicts in MATLAB

---

.github/workflows/ci.yml

They should not be not necessary anymore.

Remove workarounds for https://github.com/robotology/robotology-superbuild/issues/1139

---

.github/workflows/matlab-one-line-install-test.yml

Workaround for https://github.com/matlab-actions/run-command/issues/43
Workaround for https://github.com/robotology/robotology-superbuild/issues/1492

Do not run MATLAB tests on matlab latest/2023b version

---

CMakeLists.txt

Fix https://github.com/robotology/robotology-superbuild/issues/1505 .
Supersedes https://github.com/robotology/robotology-superbuild/pull/1506 .

Set CMP0094 to NEW

---

CMakeLists.txt

As the code in some cases return slightly different results then the previous version (see https://github.com/robotology/robotology-superbuild/issues/1238#issuecomment-1234165171), we only use it when Python >= 3.12 .
Related to https://github.com/robotology/robotology-superbuild/issues/1238 .

Fix code to obtain Python relative install dir in Python 3.12

---

cmake/BuildiDynTree.cmake

`iDynTree` that does not depend on YARP and ICUB, but it still searches them as they are used in some tests. However, in the robotology-superbuild we do not want to build iDynTree with YARP and ICUB support, so let's pass to the build some options to ensure that the YARP and ICUB support is never enabled, as it can create some problems in some corner-cases (reported by @S-Dafarra).
If you are not familiar with the `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` option, check https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html .

BuildiDynTree: Ensure that there are no cross-talking with YARP and ICUB

---

.ci/install_debian.sh
.github/workflows/ci.yml
CHANGELOG.md
README.md
apt.txt
cmake/BuildiDynTree.cmake
doc/cmake-options.md
scripts/install_apt_dependencies.sh

See https://github.com/robotology/robotology-superbuild/issues/481#issuecomment-1814495739 for the reasoning behind this choice.

 Remove Ubuntu 18.04 support from documentation and CI scripts 

---

scripts/robotologyGitStatus.sh

This will update the git log as 
```
git log -1 --format="%cr|%s|%H|%D"
```
In this command:
- `%cr`: Relative date (e.g., "2 days ago").
- `%s`: Subject.
- `%H`: Commit hash.
- `%D`: Ref names, including branches and tags.
For instance we will have
```
2 days ago|Commit message here|abcdef123456| (HEAD -> main, tag: v1.0, origin/main)
```

Add ref names, including branches and tags in robotologyGitStatus script

---

doc/conda-forge.md

fyi @S-Dafarra, currently this is blocked by https://github.com/conda-forge/libdc1394-feedstock/pull/2, once that PR is merged, we are ready to merge.

Document how to compile from source on linux-aarch64

---

.github/workflows/ci.yml
doc/conda-forge.md
doc/unsupported-homebrew-installation.md

The migration from jpeg to libjpeg-turbo (see https://github.com/conda-forge/conda-forge.github.io/issues/673) is still ongoing, but only a handful packages that are not used by robotology-superbuild or robotics packages in general, so it is safer to just switch to use `libjpeg-turbo` also here.

conda-forge: Migrate from jpeg to libjpeg-turbo

---

CMakeLists.txt

I have no idea why (probably some hard to detect CMake bug) but in some cases:
~~~cmake
project(robotology-superbuild NONE)
enable_language(C)
enable_language(CXX)
~~~
make the first call to `find_package(Python3 COMPONENTS Interpreter Development REQUIRED)` fail, while:
~~~cmake
project(robotology-superbuild LANGUAGES C CXX)
~~~
works fine (beside being a more usual form).
Fix https://github.com/robotology/robotology-superbuild/issues/1541 .
Fix https://github.com/robotology/robotology-superbuild/issues/1510 .

CMake: Specify enabled languages in project instead of calling enable_language

---

cmake/ProjectsTagsUnstable.cmake

Until the yarp-ros situation described in https://github.com/robotology/robotology-superbuild/pull/1547#issuecomment-1829415016 is fixed.
Fix https://github.com/robotology/robotology-superbuild/issues/1536 .

Pin yarp unstable branch to yarp-3.9

---

doc/conda-forge.md

Partial fix of https://github.com/robotology/robotology-superbuild/issues/1542 .

Document how to enable long path support on Windows

---

.github/workflows/ci.yml

Fix https://github.com/robotology/robotology-superbuild/issues/1542 .

Short name of build directory from build to b in conda CI

---

cmake/Buildergocub-software.cmake

Required since https://github.com/icub-tech-iit/ergocub-software/pull/196 .

Add depedency of ergocub-software on YARP

---

.github/workflows/ci.yml
doc/cmake-options.md
doc/conda-forge.md

Workaround for https://github.com/robotology/robotology-superbuild/issues/1564, it can be removed once https://github.com/casadi/casadi/issues/3527 is fixed.

Pin swig to 4.1.0 to avoid 4.2.0 casadi failure

---

doc/conda-forge.md

Fix dependency installation on ZSH

---

.github/workflows/ci.yml
cmake/Buildbipedal-locomotion-framework.cmake
doc/conda-forge.md

This completes what we started in https://github.com/robotology/robotology-superbuild/pull/1387, as now https://github.com/conda-forge/onnxruntime-feedstock/pull/56 is solved.
The corresponding change in the blf conda-forge recipe was made in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/53 .

Add dependency on onnruntime-cpp also on conda if ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS is enabled

---

README.md
doc/faqs.md

Fix https://github.com/robotology/robotology-superbuild/issues/1585 .
The idea to move the FAQs to a different page is to avoid confusing users with non-essential information.

 Move faqs from README to separate page  and add robotology-2021 channel to docs

---

cmake/BuildYARP.cmake
doc/conda-forge.md

This removes the need of passing `SKIP_ACE` manually.

Pass SKIP_ACE to YARP on macOS if using Apple Silicon

---

cmake/BuildiDynTree.cmake

Solution for https://github.com/robotology/robotology-superbuild/issues/1597, alternative to https://github.com/robotology/robotology-superbuild/pull/1598 . The main problem of  https://github.com/robotology/robotology-superbuild/pull/1598  is that it would raise a deprecation warning after https://github.com/robotology/ycm/pull/441 is merged. Instead, we can already avoid to use the `FindGLFW3` script by passing `NO_MODULE` to `find_package(glfw3)`.

Do not use find_package(glfw3) to detect if irrlicht+sdl is available

---

.vscode/settings.json
cmake/RobotologySuperbuildOptions.cmake

In this PR I add the VSCode `settings.json` and the CMake options needed to enable the intellisense integration for the superbuild.
See https://github.com/robotology/robotology-superbuild/issues/1596 for the discussion.

Add vscode settings

---

.github/workflows/ci.yml
cmake/BuildYARP.cmake
doc/conda-forge.md

The pin was added in https://github.com/robotology/robotology-superbuild/pull/1538 as a workaround for https://github.com/robotology/robotology-superbuild/issues/1537, as the proper fixes have been released, we should be able to just drop the pin and use graphviz 9, to avoid incompatibility with libraries that actually use graphviz 9.

Remove pin of graphviz to 8 and disable yarpviz compilation on conda until YARP 3.10.0 is released

---

cmake/ProjectsTagsUnstable.cmake

As in https://github.com/robotology/robotology-superbuild/pull/1549 we temporary pinned yarp in unstable branches to 3.9, for the same reason we need to pin also yarp-matlab-bindings .

Also set yarp-matlab-bindings_TAG unstable to yarp-3.9

---

.github/workflows/ci.yml
conda/cmake_recipe_template/meta.yaml
conda/conda_build_config.yml
doc/conda-forge.md

Fix issue similar to https://github.com/robotology/idyntree/issues/1156 but for the superbuild. As a cleanup, I also migrated as much as cdt as possible to regular packages.

Switch expat, xcb and xorg libraries from cdt to proper packages and add xorg-libxrandr package for glfw 3.4

---

cmake/BuildICUB.cmake

This device has been removed here:
- https://github.com/robotology/icub-main/pull/916
After that it has completely made obsolete by:
- https://github.com/robotology/icub-main/pull/894
- https://github.com/robotology/robots-configuration/pull/540

Remove embObjInertials

---

cmake/Buildergocub-software.cmake

ergocub-software: compile ergoCubEmotions by default if OpenCV >= 4.5.2

---

cmake/Buildyarp-devices-forcetorque.cmake
cmake/Buildyarp-devices-ros.cmake
cmake/RobotologySuperbuildLogic.cmake
releases/latest.releases.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1617 .
~Blocked by https://github.com/robotology/yarp-devices-ros/pull/2 and by having a tag to also update the `latest.releases.yaml` file.~ Solved: https://github.com/robotology/yarp-devices-ros/releases/tag/v3.9.0 .
fyi @dariosortino @S-Dafarra

Add yarp-devices-ros repo

---

.vscode/settings.json

I was having problems with the mergedCompileCommands setting: the expression was not evaluated correctly and so the file was generated in the wrong folder.
This should correct the behaviour.

Fix settings.json cmake merged commands location

---

cmake/RobotologySuperbuildOptions.cmake

When compiling on Windows with conda-forge dependencies, it is not supported compiling in Debug. The problem is that if a users try to compile in Debug, a really difficult to interpret error occurs, something like:
~~~
FAILED: bin/idjl_camera_model.dll lib/idjl_camera_model.lib
cmd.exe /C "cmd.exe /C "C:\Users\straversaro\AppData\Local\miniforge3\envs\idjlenv\Library\bin\cmake.exe -E __create_def C:\src\idjl-software\build\cxx\libraries\idjl-camera-model\CMakeFiles\idjl_camera_model.dir\.\exports.def C:\src\idjl-software\build\cxx\libraries\idjl-camera-model\CMakeFiles\idjl_camera_model.dir\.\exports.def.objs && cd C:\src\idjl-software\build" && C:\Users\straversaro\AppData\Local\miniforge3\envs\idjlenv\Library\bin\cmake.exe -E vs_link_dll …

Add check to prevent compilation in Debug on Windows with conda-forge dependencies

---

.github/workflows/ci.yml
apt-python.txt
cmake/Buildmeshcat-python.cmake
cmake/Buildpyngrok.cmake
doc/conda-forge.md
releases/latest.releases.yaml

We were missing some dependencies needed for the robot-log-visualizer.

Add missing dependencies for robot-log-visualizer

---

.github/workflows/ci.yml
README.md
apt.txt
scripts/install_apt_dependencies.sh

This will be required to support YARP 3.10, as otherwise we do not have easy and maintainable way of installing CMake in the version that will be required by YARP 3.10.
This was added in https://github.com/robotology/robotology-superbuild/pull/1547, but I separate it in a separate PR to better visibility. 
**IMPORTANT: This change will make future robotology-superbuild releases not compatible with pc104-based iCub robots, as the last available image for pc104 is based on Debian 10 Buster, see https://icub-tech-iit.github.io/documentation/icub_operating_systems/pc104/icub-live/#versioning .**
As Debian 10 uses glibc 2.28 (see https://repology.org/project/glibc/versions), it should be possible to install software with conda-forge dependencies on Debian 10 for some time in the future. …

Drop Debian 10 Buster support

---

.github/workflows/matlab-one-line-install-test.yml

* Switch macos jobs to use macos-13, macos-latest is now macos-14 that uses osx-arm64, and we do not have osx-arm64 matlab binary packages
* Switch the job to only run bi-weekly on schedule, that logic seldomly changes so it does not make sense to run the CI at every PR or commit

Fix matlab-one-line-install-test CI job

---

.ci/install_debian.sh
.github/workflows/ci.yml
CMakeLists.txt
README.md
cmake/BuildICUB.cmake
cmake/BuildYARP.cmake
cmake/RobSupPurePythonYCMEPHelper.cmake
cmake/RobotologySuperbuildLogic.cmake
cmake/RobotologySuperbuildOptions.cmake
doc/cmake-options.md

Fix https://github.com/robotology/robotology-superbuild/issues/1641 .
Main changes on the superbuild side:
* yarp and icub-main Python bindings do not work with the SWIG 4.2.0 version (see https://github.com/swig/swig/issues/2796), that is installed by apt on Ubuntu 24.04. To get the superbuild to work on Ubuntu 24.04 with apt dependencies, the superbuild CMake machinery downloads and uses for yarp and icub-main a private swig 4.2.1 (that is only used inside the superbuild, not exposed if one sources the `setup.sh` of the superbuild). The logic is specific for Ubuntu 24.04 with apt dependencies, as all other Debian distributions either have a newer or older swig version, that are not affected by the problem (see https://repology.org/project/swig/versions). Note that for local builds of …

Add build with apt dependencies from Ubuntu 24.04 to docker-build CI

---

.ci/install_debian.sh
.github/workflows/ci.yml
README.md
doc/cmake-options.md

See https://community.gazebosim.org/t/gazebo-harmonic-packages-available-on-ubuntu-noble/2772 .

Enable ROBOTOLOGY_USES_GZ_SIM with apt dependencies on Ubuntu 24.04

---

.github/workflows/ci.yml
doc/conda-forge.md

YARP has some compilation issues with ffmpeg==7, the fix is provided in https://github.com/robotology/yarp/pull/3109 but it will take some time for it to be merged and released, so in the meanwhile let's fix ffmpeg to 6.* .

Pin ffmpeg to 6.*

---

.github/workflows/ci.yml
.github/workflows/generate-conda-packages.yaml
doc/cmake-options.md
doc/conda-forge.md
doc/conda-powershell-troubleshooting.md
doc/faqs.md
doc/install-miniforge.md
scripts/install_robotology_packages.m

Back in time when we started using conda (~2020/2021?), the conda tool was extremely slow, and that is the reason why mamba was developed, and why we suggested everyone to use mamba. Similarly, we suggested to install mambaforge as a distribution instead of miniforge3, as mambaforge contained by default. See https://github.com/robotology/robotology-superbuild/pull/847 for the related PR.
Since those days, a lot of changed. conda has  been updated to use the mamba solver, and so it has become much faster and more and less as fast as mamba . This is true that as long as you have a recent enough `conda`, to verify that check that the commands conda config --show solver returns solver: libmamba, see https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community .
For this reason, …

Suggest to use conda and miniforge instead of mamba and mambaforge

---

.github/workflows/ci.yml
doc/conda-forge.md

Fix https://github.com/robotology/robotology-superbuild/issues/1666 and ensure that the conflicts results in clearer errors in the future.

Explicitly install qhull and specify minimum version for pcl

---

.github/workflows/ci.yml
cmake/ProjectsTagsStable.cmake
releases/latest.releases.yaml

Historically, ycm-cmake-modules have been carrying on a patched version of CMake's ExternalProject module that made sure that it was never possible for ExternalProject to delete a source directory of a repo (the one contained in `robotology-superbuild/src/<package>`) if one had local modifications and it did not set `YCM_EP_DEVEL_MODE_<package>` to `ON` . For more details, see: 
* The part of CMake code that actually deletes a folder: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.30.0/Modules/ExternalProject/shared_internal_commands.cmake?ref_type=heads#L1005-L1029).
* The long discussion of this YCM local modification: https://github.com/robotology/ycm-cmake-modules/issues/50
Unfortunately, the modification was never merged upstream, and it is not anymore possible for me to keep the …

Pass YCM_USE_CMAKE_NEXT set to OFF in normal-build (i.e. apt with gha image and vcpkg on windows) workflow and bump YCM to v0.16.5

---

doc/cmake-options.md
doc/conda-forge.md

Somewhere in the documentation the option was erroneously called `ROBOTOLOGY_USES_GZ_SIM`

Align option name `ROBOTOLOGY_USES_GZ`

---

.github/workflows/ci.yml
CMakeLists.txt
README.md

Historically, ycm-cmake-modules have been carrying on a patched version of CMake's ExternalProject module that made sure that it was never possible for ExternalProject to delete a source directory of a repo (the one contained in `robotology-superbuild/src/<package>`) if one had local modifications and it did not set `YCM_EP_DEVEL_MODE_<package>` to `ON` . For more details, see: 
* The part of CMake code that actually deletes a folder: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.30.0/Modules/ExternalProject/shared_internal_commands.cmake?ref_type=heads#L1005-L1029).
* The long discussion of this YCM local modification: https://github.com/robotology/ycm-cmake-modules/issues/50
Unfortunately, the modification was never merged upstream, and it is not anymore possible for me to keep the …

Set YCM_USE_CMAKE_NEXT to OFF by default to use upstream CMake's ExternalProject instead of YCM's fork

---

.github/workflows/ci.yml

Fix https://github.com/robotology/robotology-superbuild/issues/1680 .

Force CMAKE_CONFIGURATION_TYPES to Debug;Release in vcpkg build

---

cmake/Buildosqp.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1083 .
To do so, it was necessary to fix support for building shared libraries and disabling static libraries in osqp 0.6.3, this was already done since a lot of time in osqp master, but as long as we do not get a release of osqp, we continue to use osqp 0.6.3 . The related commits are:
* https://github.com/robotology-dependencies/osqp/commit/060751ffcca0d0f2b800baf09b2e067310d9ddb2
* https://github.com/robotology-dependencies/qdldl/commit/3770026c0546216df29c0ea37102df20d33f2ba5

Fix support for building on Windows with Ninja

---

CMakeLists.txt

Hotfix so for https://github.com/robotology/robotology-superbuild/issues/1690 so we can work on a proper solution without all the CI red.

Pin YCM to v0.16.6 to workaround YCM regression

---

.github/workflows/ci.yml
CMakeLists.txt

It should not be necessary after https://github.com/robotology/ycm-cmake-modules/pull/458 .

Remove pin of YCM

---

pixi.lock
pixi.toml

The default version of pixi 0.27.1 is `5.10`, and so running anything on a HPC system running Rocky Linux 8 results in errors like:
~~~
× The current system has a mismatching virtual package. The project requires '__linux' to be at least version '5.10' but the system has version '4.18.0'
~~~
xref: https://github.com/prefix-dev/pixi/issues/1884

pixi: Lower minimum linux kernel version required to 4.18

---

doc/faqs.md

We took some time with @giotherobot to debug this error today:
~~~
OSError: [WinError 182] The operating system cannot run %1. Error loading "D:\miniforge\envs\robsub\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
~~~
that we had when trying to load `import torch`. This was because we had both `openmp` and `intel-openmp` installed in your conda environment.
This may not be the perfect place, but we owe humanity to put this information somewhere reachable.
See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1359 for more infomation.
xref:
* https://github.com/conda-forge/flang-feedstock/issues/26
* https://github.com/conda-forge/intel_repack-feedstock/issues/59
* https://github.com/ContinuumIO/anaconda-issues/issues/13146
* …

Add pytorch on Windows related info to faqs

---

.github/workflows/generate-conda-packages.yaml
conda/conda_build_config.yml

The pin were added (see https://github.com/robotology/robotology-superbuild/pull/1606 and https://github.com/robotology/robotology-superbuild/pull/1578) because the migrations were ongoing, but both respective migrations have been completed since a long time. 
Hopefully this should help for https://github.com/robotology/robotology-superbuild/issues/1670 .

Remove ipopt and libxcb pinning from conda_build_config.yml

---

.github/workflows/pixi-ci.yml
cmake/Buildcasadi.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

Since casadi 3.6.6 includes https://github.com/casadi/casadi/pull/3724, we can now switch back to use the main casadi repository. The only fix we added on top of it is https://github.com/casadi/casadi/pull/3832, but at the moment we did not enable fatrop in the superbuild (while we enabled it on conda-forge on Linux, see https://github.com/conda-forge/casadi-feedstock/pull/115), so we can just keep using 3.6.6 . 
Fix https://github.com/robotology/robotology-superbuild/issues/1714 .

Update casadi to 3.6.6 and stop using ami-iit fork

---

.github/workflows/generate-conda-packages.yaml
conda/cmake/CondaGenerationOptions.cmake
doc/conda-forge.md

This permit us to keep latest packages on `robotology` channel on anaconda.org so that `-c robotology` continue to work for latest packages even on vanilla conda, but we keep the full history of packages in prefix.dev robotology.
To kickstart the upload, I used the following two scripts (that I do not upload in the repo as they will not be necessary in the future):
`download_all.sh`:
~~~sh
conda-mirror --upstream-channel robotology --target-directory robotology_mirror --platform noarch
conda-mirror --upstream-channel robotology --target-directory robotology_mirror --platform linux-64
conda-mirror --upstream-channel robotology --target-directory robotology_mirror --platform osx-64
conda-mirror --upstream-channel robotology --target-directory robotology_mirror --platform win-64
~~~ …

 Document the new prefix.dev robotology channel mirror  and upload new robotology conda packages to both anaconda.org and prefix.dev

---

doc/cmake-options.md

I modified the code to fail with no effect on non-Windows and non-superbuild installation, so that the snippet can be added to any script without preventing to run the script in context different from a Windows superbuild install.

Cleanup Python snippet required to run Python bindings on Windows

---

.github/workflows/generate-conda-packages.yaml
.github/workflows/generate-non-periodical-conda-package.yaml
conda/cmake/CondaGenerationOptions.cmake

Follow up of https://github.com/robotology/robotology-superbuild/pull/1716 .

Add missing pixi dependency in generate-conda-packages and missing prefix.dev upload to generate-non-periodical-conda-package job

---

.github/workflows/generate-conda-packages.yaml
.github/workflows/generate-non-periodical-conda-package.yaml
doc/conda-forge.md

At least in `ami-iit` lab no one is using anymore Intel macOS laptops, and all macOS users have Apple Silicon laptops. For this reason, we switch the generation of robotology conda binary packages to target `osx-arm64` instead of `osx-64` . Note that this does not affect packages that are built by conda-forge. Indeed, if you are actually a users of one package from the `robotology` channel on `osx-64`, feel free to comment here, probably the easiest way to support any package that you still use is to migrate its conda binary package from the `robotology` channel to the `conda-forge` one.

Switch robotology conda binary packages generation to target osx-arm64 instead of osx-64

---

conda/cmake_recipe_template/build.sh

Currently conda packages build on osx-arm64 fail with error:
~~~
2024-10-03T20:47:09.6134360Z CMake Error at /Users/runner/miniconda3/envs/test/conda-bld/walking-controllers_1727988336360/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:258 (message):
2024-10-03T20:47:09.6136720Z   To use a cross-compiled Qt, please set the QT_HOST_PATH cache variable to
2024-10-03T20:47:09.6137370Z   the location of your host Qt installation.
2024-10-03T20:47:09.6137790Z Call Stack (most recent call first):
~~~
This is due to https://github.com/conda-forge/qt-main-feedstock/issues/273 . As a workaround, we add …

conda: Set QT_HOST_PATH in conda's build.sh CMake template for osx-arm64 compat

---

cmake/YCMBootstrapFetch.cmake
releases/latest.releases.yaml

This will remove all the noisy warnings:
~~~
CMake Warning (dev) at D:/miniforge3/envs/robsub/Library/share/[cmake-3](https://gitlab.kitware.com/cmake/cmake/-/issues/3).30/Modules/FetchContent.cmake:1953 (message):
Calling FetchContent_Populate(YCM) is deprecated, call
FetchContent_MakeAvailable(YCM) instead. Policy CMP0169 can be set to OLD
to allow FetchContent_Populate(YCM) to be called directly for now, but the
ability to call it with declared details will be removed completely in a
future version.
Call Stack (most recent call first):
cmake/YCMBootstrapFetch.cmake:103 (FetchContent_Populate)
CMakeLists.txt:60 (include)
~~~
in recent CMake releases.

Update YCMBootstrapFetch.cmake to avoid CMP0169 related warnings and update YCM to 0.17.1

---

cmake/BuildBlockFactory.cmake
cmake/BuildQpSolversEigen.cmake
cmake/BuildWBToolbox.cmake
cmake/Buildsharedlibpp.cmake
releases/latest.releases.yaml

This PR adds `qpsolvers-eigen` and `sharedlibpp` to the superbuild, in view of the integration of `qpsolvers-eigen` to WBToolbox.
Furthermore, as `qpsolvers-eigen` depends on `sharedlibpp`, this PR also updates BlockFactory and WBToolbox to 1.0.0 and 6.0.0, that are the versions that are compatible with the external `sharedlibpp`. Before blockfactory 1.0.0, blockfactory had an internal library called shlibpp that was also used by WBToolbox. This library is not substituted by sharedlibpp.

Add qpsolvers-eigen and sharedlibpp to the robotology-superbuild

---

cmake/Buildrobometry.cmake

In `telemetryDeviceDumper` it has been added the usage of `IRawValuesPublisher` by @MSECode, this made the device dependent also by ICUB 2.7.0 or higher.
I am unsure if the superbuild compiles the device right now, because if the dependencies are not found the compilation of the device is skipped.
See:
- https://github.com/robotology/robometry/pull/190
cc @traversaro @S-Dafarra @valegagge

Update Buildrobometry.cmake after the addition of IRawValuesPublisher

---

cmake/RobotologySuperbuildLogic.cmake

Until https://github.com/robotology/idyntree-yarp-tools/issues/50 is fixed.

Disable generation of conda packages for idyntree-yarp-tools

---

.github/workflows/ci.yml

The `macos-12` is now deprecated and will be removed soon, see https://github.com/actions/runner-images/issues/10721 . To continue testing macOS with Intel processor, we can switch to use `macos-13`.

CI: Replace deprecated macos-12 images with macos-13

---

cmake/BuildYARP.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/1762 .
The problem was two-fold:
* There was a typo in which `YARP_OPTIONAL_DEPS` was used in place of `YARP_OPTIONAL_CMAKE_ARGS`
* Differently from other libraries, the `CMAKE_INSTALL_PYTHON3DIR` is a PATH CACHE variable, so if we pass a relative path, it gets automatically expanded to the absolute path w.r.t. to the current work directory where cmake is invoked, while we want it to be relative w.r.t. `${YCM_EP_INSTALL_DIR}` (i.e. the variable that is passed as `CMAKE_INSTALL_PREFIX` to all projects)

Fix installation directory of YARP python bindings

---

cmake/Buildyarp-device-openxrheadset.cmake

See https://github.com/ami-iit/yarp-device-openxrheadset/pull/56 for more details.

Add missing xorg-xorgproto dependency in yarp-device-openxrheadset

---

README.md

Fix ycm broken links in README.md

---

.github/workflows/ci.yml

Workaround for https://github.com/robotology/robotology-superbuild/issues/1783 .

Do not run CI of ROBOTOLOGY_PROJECT_TAGS=Unstable on Ubuntu 20.04 with apt dependencies

---

.github/workflows/pixi-ci.yml

With https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ we finally have GitHub Action CI on Linux arm64!

Enable pixi-ci on linux-aarch64

---

pixi.toml

The `depends-on` syntax was supported since pixi 0.21 (see https://github.com/prefix-dev/pixi/pull/1310), so there risk of creating troubles to any user with an old pixi is non existent, as anyhow the lock file version that we used is newer if I am not wrong.
This should reduce the amount of warnings printed on the terminal of @AntonioViscomi .

Change depends_on with depends-on in pixi.toml

---

pixi.toml

@AntonioViscomi was reporting some problem when trying to switch some subprojects of the superbuild to `RelWithDebInfo`. By looking at the pixi.toml, I noticed that the information on the CMake build type was duplicated everywhere, while probably it is simpler to just set once the [`CMAKE_BUILD_TYPE`](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) env variable.

pixi: Use a single CMAKE_BUILD_TYPE env variable to set the build type

---

cmake/BuildResolveRoboticsURICpp.cmake

Due to a typo in https://github.com/robotology/robotology-superbuild/pull/1791, YCM was downloaded instead lf ami-iit/resolve-robotics-uri-cpp . FYI @isorrentino

Fix URL and branch in BuildResolveRoboticsURICpp

---

cmake/RobSupPurePythonYCMEPHelper.cmake

When rob_sup_pure_python_ycm_ep_helper  was added in https://github.com/robotology/robotology-superbuild/pull/1069, the installation of package was done locally via `pip install`, and by passing `--no-deps` to ensure that all the used dependencies were installed either via apt or via the robotology-superbuild, to avoid regressions due to newer version of the dependencies installed. 
That was correct, but back in time we forgot that packages are installed from PyPI (at their latest version) also when creating the isolated venv used to build the package (as described by https://peps.python.org/pep-0517/). This recently created a regression due to the conflict of versions between apt and the isolated venv used to build (see https://github.com/robotology/robotology-superbuild/issues/1804) so …

Pass --no-build-isolation to pip in rob_sup_pure_python_ycm_ep_helper 

---

.github/workflows/ci.yml
.github/workflows/generate-conda-packages.yaml
.github/workflows/generate-non-periodical-conda-package.yaml
.github/workflows/update-latest-releases.yml
README.md
apt.txt
cmake/Buildbipedal-locomotion-framework.cmake
cmake/RobotologySuperbuildLogic.cmake
doc/cmake-options.md
scripts/install_apt_dependencies.sh

YARP 3.11 is not supporting anymore Ubuntu 20.04 with apt dependencies, so as preliminary step for updating to YARP 3.11 we also drop support here. Ubuntu 20.04 users can use conda depenencies if they watn to use newer versions of robotology-superbuild.
Fix https://github.com/robotology/robotology-superbuild/issues/1439 .

Drop support for apt dependencies on Ubuntu 20.04

---

cmake/Buildyarp-device-openxrheadset.cmake

`yarp-device-openxrheadset` has a optional dependency on iDynTree (see https://github.com/ami-iit/yarp-device-openxrheadset/blob/639803744f63a8496e417861300eac7ad31e0da0/src/utils/CMakeLists.txt#L7-L9), so without an explicit dependency what is actually build is actually subject to a race condition: if `yarp-device-openxrheadset` is built before `iDynTree` it is built without `iDynTree` support, if it is built after it is with with `iDynTree` support. To avoid the race condition, we just add the dependency.

Add iDynTree dependency to yarp-device-openxrheadset

---

cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake

Furthermore also update casadi in Stable and Unstable branches to 3.6.7 as it remained in 3.6.6 there (leftover from https://github.com/robotology/robotology-superbuild/pull/1725).
I did not bumped YARP in latest releases to 3.11.1 as we are blocked on https://github.com/robotology/yarp-devices-ros2/issues/80 .

Bump YARP in Stable and Unstable branches to 3.11.1

---

conda/cmake/CondaGenerationOptions.cmake
doc/conda-forge.md

As we are running out of space on anaconda.org's robotology channel, let's document that that channel only hosts packages built after July 2023, while for all packages interested users should use https://prefix.dev/channels/robotology .

Document that anaconda.org's robotology channel only contains packages from July 2023

---

README.md
cmake/BuildQpSolversEigen.cmake
cmake/Buildcasadi.cmake
cmake/ProjectsTagsStable.cmake
releases/latest.releases.yaml

* Fix build of ROBOTOLOGY_USES_ROS2 on Stable branches by pinning yarp-devices-ros2 with a version compatible with YARP 3.11
* Fix build of HDE on Windows with LatestRelease and VS 17.13 by bumping version to 4.2.1 that includes https://github.com/robotology/human-dynamics-estimation/pull/423
* Bump YCM to v0.18.2
Fix https://github.com/robotology/robotology-superbuild/issues/1814 .

Fix various CI issues of late february 2025

---

.github/workflows/ci.yml

In the last months we had frequengly segfaults when using conda install on Windows. This CI upgrades the used version of mamba to 2.*, to check if that fixes the segfaults.

Use latest conda and conda-libmamba-solver to avoid segfaults on Windows

---

.github/workflows/ci.yml

I was aware we were missing the `LatestReleases` CI with conda, but we nefer have problem. We experienced the first problem in https://github.com/robotology/robotology-superbuild/issues/1708, so let's enable it. To reduce the amount of jobs anyhow, in the same PR we change fail-fast to true, to avoid wasting CI jobs in non-necessary builds.

 Add conda + LatestReleases CI build  and switch fail-fast option to true

---

cmake/Buildrobometry.cmake

Now that we dropped support for Ubuntu 20.04 with apt dependencies, we can drop the need for manually downloading and compiling nlohmman_json as part of robometry (see https://github.com/robotology/robometry/blob/v1.2.6/CMakeLists.txt#L72-L89).
This should speedup the configuration time of robometry.

Enable ROBOMETRY_USES_SYSTEM_nlohmann_json when building robometry

---

conda/multisheller/human-gazebo_activate.msh
conda/multisheller/human-gazebo_deactivate.msh

The `human-gazebo` repo install URDF files that use the `package://` URIs, so we need to make sure that `AMENT_PREFIX_PATH` is defined to ensure that the URIs are correctly resolved. We only set `AMENT_PREFIX_PATH` and not env variables related to gz-sim, ROS 1 or Gazebo Classic  we do not envison that these URDF files are used there.

Fix set of AMENT_PREFIX_PATH environment in conda package of human-gazebo

---

.github/workflows/generate-conda-packages.yaml
.github/workflows/generate-non-periodical-conda-package.yaml
conda/cmake/CondaGenerationOptions.cmake

After migration to rattler-build done https://github.com/robotology/robotology-superbuild/pull/1821, the packages are created as `.conda` packages, not anymore as `.tar.bz2`. So there was some upload-related code that needed to be modified, this PR fixes that.

Fix upload of conda packages after migration to rattler-build

---

cmake/BuildOsqpEigen.cmake

Similar to https://github.com/robotology/robotology-superbuild/pull/1452, required after https://github.com/robotology/osqp-eigen/pull/189 .

Fix configuration of osqp-eigen with multiple-config CMake generators

---

cmake/BuildOpenVR.cmake
cmake/Buildbipedal-locomotion-framework.cmake
cmake/Buildosqp.cmake
releases/latest.releases.yaml

Fix https://github.com/robotology/robotology-superbuild/issues/1831 .
Specific fixes:
* [Fix compilation of osqp with CMake 4.0.0 by passing -DCMAKE_POLICY_VERSION_MINIMUM=3.10](https://github.com/robotology/robotology-superbuild/pull/1832/commits/80acc7245e2ab42f3475369da1ee0402f5511940)

Fix compilation of robotology-superbuild with CMake 4.0.0

---

README.md

The path of the `setup.sh` script used in apt instructions was wrong, and was wrong since it was added in https://github.com/robotology/robotology-superbuild/pull/1547 . 
The equivalent instructions in the conda instructions was already correct, so we do not need to fix it.
Thanks @kaidegast for the report.

Fix path of setup.sh in installation instructions

---

.github/workflows/ci.yml

The pin was added in https://github.com/robotology/robotology-superbuild/pull/1818, but since then new release of miniforge were released, and as we saw other failures (https://github.com/robotology/robotology-superbuild/issues/1843) let's check if this helps.
Fix https://github.com/robotology/robotology-superbuild/issues/1843 .

CI: Remove hardcoding specific miniforge3 version

---

CMakeLists.txt

Add a workaround for https://github.com/conda-forge/qt-main-feedstock/issues/275 . In a nutshell, qt6 executable that are not installed in `%CONDA_PREFIX%\Library\bin` on Windows fail with error:
~~~
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
~~~
At the moment (unfortunately) we do not have a lot of qt6 executables in the robotology-superbuild, but any executable that calls for example OpenCV's `cv::imshow` with a recent build of opencv (that uses qt6 under the hood) would trigger the error, so this workaround should work.

Add workaround for ensuring that executables that use qt6 work on Windows

---

cmake/BuildYARP.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/1604 .

Remove graphviz and YARP 3.9 workaround

---

cmake/BuildOsqpEigen.cmake
cmake/Buildcasadi.cmake
cmake/Buildosqp.cmake
cmake/ProjectsTagsStable.cmake
cmake/ProjectsTagsUnstable.cmake
releases/latest.releases.yaml

To permit to generate again conda packages for the `robotology` channel, we need to align with the osqp version used in conda-forge, that is now osqp v1. At the moment this PR does not do that as latest releases still uses osqp v1, waiting for a blf release.
To do this, we also need to switch back to use a casadi fork that incorporates https://github.com/casadi/casadi/pull/4105 .

Upgrade osqp to v1.0.0 in LatestReleases and Stable, Unstable branches

---

CMakeLists.txt
README.md
cmake/template/deactivate.bat.in
cmake/template/deactivate.sh.in
cmake/template/setup.sh.in
doc/conda-forge.md
doc/deprecated-installation-methods.md
doc/environment-variables-configuration.md

Fix https://github.com/robotology/robotology-superbuild/issues/1498 . 
This PR adds a  `./build/install/share/robotology-superbuild/deactivate.sh` and `./build/install/share/robotology-superbuild/deactivate.bat` scripts, to complement the existing `./build/install/share/robotology-superbuild/setup.sh` and `./build/install/share/robotology-superbuild/setup.bat` that are used to set all the env variables required by the superbuild. 
In particular, the new scripts are useful in context where a conda environment + superbuild environment is already activated, for example inside a `.bashrc` with : 
~~~
conda activate robsub
source ./build/install/share/robotology-superbuild/setup.sh
~~~
if you want to activate a new conda environment, to avoid cross-talking your first need to deactivate the …

Add deactivation scripts for sh and Command Prompt

---

cmake/BuildICUB.cmake

As per title.
This would come handy since these devices has been added to the icub_all.xml of iCubGenova11:
- https://github.com/robotology/robots-configuration/pull/748
Xref:
- https://github.com/robotology/icub-main/pull/1034
cc @MSECode @pattacini

Add in BuildICUB.cmake rawValuesPublisheServer/Client and fineCalibrationChecker

---

releases/2025.08.0.yaml
releases/latest.releases.yaml

As per the title.
Once merged, we may want to cherry pick this commit onto `master`, @traversaro

Fixed wrong link of Simulink Arsenal
